### ISSUE TITLE
npm install -g fails on Windows

### ISSUE THREAD

**Issue by bubenshchykov** [bubenshchykov/ngrok#10]
npm install ngrok -g
ngrok

>> /c/Users/syan.KYIV/AppData/Roaming/npm/ngrok: line 1: /node_modules/ngrok/bin/ngrok: No such file or directory

i thought it should be fixed by having ngrok.cmd what calls ngrok.exe in bin, but it doesn't work

an option is to have _ngrok.js in bin what just runs a unix-bin or win32-bin via child_process

**Comment by artemsvirskyi** [comment]
I have the same issue on windows

**Comment by marcofugaro** [comment]
Yup, same problem in windows too, how do I solve this?

**Comment by bubenshchykov** [comment]
@artemsvirskyi @marcofugaro if you guys use ngrok as executable outside the node - you better use it directly https://ngrok.com/download

but would be nice if some of you tries to create a proper windows wrapper, with .cmd file or so - as I have mac only. http://stackoverflow.com/questions/29955217/global-npm-package-installed-but-command-not-found

**Comment by marcofugaro** [comment]
@artemsvirskyi yeah I managed to make it work by downloading the `ngrok.exe`, but yet again it wouldn't run in my git bash and I don't know why, it doesn't output anything when I type `./ngrok.exe http 80`, so had to run it from the windows command line...

I just want to use it anywhere by typing `ngrok http 80`, it used to work on my other machine when I installed it globally with node, now it has this problem which your stackoverflow suggestion didn't help.

Yes will look more into this issue, what do you mean by a proper wrapper? I can see the ngrok.cmd in the `C:\Users\Marco\AppData\Roaming\npm`

**Comment by bubenshchykov** [comment]
installing it globally from npm has been tested and works for linux machines, but was never working for windows. this .cdm thing doesn't work, i'm not sure why, maybe smth from with paths or so

i'll reopen the issue and wait for winodws volunteers

**Comment by bubenshchykov** [comment]
the issue has been here for quite a while with no volonteers to fix, closing as not popular

**Comment by lyzs90** [comment]
you can create a .bash_profile in your HOME directory and then add the path to your ngrok.exe
```
cd ~
touch .bash_profile
```
add the relative path to your ngrok bin directory to the PATH variable: `PATH=$PATH:~/AppData/roaming/npm/node_modules/ngrok/bin`

now you should be able to run ngrok anywhere using `ngrok.exe`

**Comment by mikiasgv** [comment]
Just try it from windows cmd.

**Comment by heroys6** [comment]
I installed npm, trying: `npm install ngrock -g` and got: `npm ERR! 404 Not Found: ngrock@latest`

**Comment by bubenshchykov** [comment]
hi, the name of module is ngrok, not ngrock :)

**Comment by TLmaK0** [comment]
With git bash use:

```ngrok.cmd http 80``` instead of ```ngrok http 80```

**Comment by silviujingoi** [comment]
I added the following alias to my `~/.bash_profile`

`alias ngrok="ngrok.cmd http --log=stdout"`

After that you can just run `ngrok 80` to create the HTTP tunnel.

**Comment by claridgicus** [comment]
> With git bash use:
> 
> `ngrok.cmd http 80` instead of `ngrok http 80`

Thank some deity for you - so annoying though

**Comment by PeterTough2** [comment]
> 
> 
> With git bash use:
> 
> `ngrok.cmd http 80` instead of `ngrok http 80`

If this fails on Windows, navigate to `C:\Users\Your-User\AppData\Roaming\npm\node_modules\ngrok\bin` and double click on `ngrok.exe` to run, then enter `ngrok.exe http YOUR-PORT`

**Comment by guidosantillan01** [comment]
> With git bash use:
> 
> `ngrok.cmd http 80` instead of `ngrok http 80`

That worked. Thanks!

**Comment by ibrahim0099** [comment]
Open Window Prompt as an administrator & then run this command. That will work.

ngrok http 3000

**Comment by zek7rom** [comment]
Go to https://ngrok.com/  create an account, download the ngrok zip file off the website, unzip the file. Then go in your Command Prompt and cd to that folder, once you do that, do "ngrok" to make sure it gives you a list of all the commands, it will also tell you the version of ngrok you install etc. From there type "ngrok http 80" and it should work.
