### ISSUE TITLE
Reset state if ngrok exits

### ISSUE THREAD

**Issue by dobesv** [bubenshchykov/ngrok#104]
If `ngrok` exits with some kind of error (for example, `you are already running as many ngrok processes as you are allowed to`) then calling `connect()` again just results in an error that it can't talk to ngrok on port 4040.  It never tries to restart `ngrok`.  It would be nice if in the `ngrok.on('close', ...)` it would set `api = null` so that a future `connect` call will re-run `ngrok`.

**Comment by bubenshchykov** [comment]
Makes sense. We can reset it (re-spawn ngrok) in case of error AND if there are no active tunnels running. Otherwise resetting ngrok will kill active tunnels.

**Comment by dobesv** [comment]
@bubenshchykov My contention here is actually what to do if ngrok exits on its own for whatever reason.  Maybe there's an outage at ngrok HQ or I killed it myself using the command line.  In that case this library can detect that `ngrok` has exited and at least try to start it again if I call `connect`.  Currently if ngrok dies on its own, then calling `connect` returns an error that it cannot connect to `ngrok`.

Your workaround would probably work, though, I'll try it.

**Comment by dobesv** [comment]
I think what I can do to workaround this might be:

```
  // Make sure ngrok state is reset if ngrok exits
  // See also https://github.com/bubenshchykov/ngrok/issues/104
  ngrok.once('close', () => {
    ngrokUrl = null;
    ngrok.kill();
  });
```

Since I think if I run `ngrok.kill()` I can use `connect()` again afterwards.

**Comment by dobesv** [comment]
Actually no, that doesn't work.

You see, in `kill()` it waits for `ngrok.on('exit', ...)`.  However, since ngrok has already exited, that event does not fire.  Thus calling `ngrok.kill()` if `ngrok` has already quit does not reset `api = null` as would be needed to have `ngrok` restart on the next `connect`.

I think the event handler for `ngrok.on('exit', ...)` should be moved up into the `runNgrok()` function so that any time ngrok exits (whether you called `kill` or not) it sets `api = null`.

**Comment by bubenshchykov** [comment]
Makes sense! I pushed an update to npm
