### ISSUE TITLE
Running test suite deletes ngrok config

### ISSUE THREAD

**Issue by dobesv** [bubenshchykov/ngrok#105]
I was going to see if I could make a little patch and I ran the test suite. Much to my surprise, it deleted my actual `ngrok` config, with no warning or backup.  This is kind of ... impolite ?

**Comment by bubenshchykov** [comment]
@dobesv thanks for reporting that and sorry for problems caused - I never thought about this case before. will fix when time permits, or feel free to submit your pr

**Comment by bubenshchykov** [comment]
Fixed. Unfortunately, I haven't found a way to omit rewriting/killing ngrok config
But at least now test suite ensures that it is restored after test run (even if process crashes)
