### ISSUE TITLE
ngrok and electron

### ISSUE THREAD

**Issue by cvalenzuela** [bubenshchykov/ngrok#106]
I'm not sure if this issue is specific to this package, but it's worth to give it a try:

I made an [electron app](https://github.com/cvalenzuela/carbon) that uses ngrok to create a server with a sharable url. Everything works fine, but when I package the application for production, ngrok is the only package that does not get exported to the final app. Any ideas on what might be not working? 

[Here](https://github.com/cvalenzuela/carbon/blob/master/app/components/Toolbar.js#L8) is the specific file that imports ngrok

**Comment by bubenshchykov** [comment]
I haven't played with electron yet, but take a look at similar issues ("electron module not found in prod"), there might be some clues 
https://github.com/electron-userland/electron-packager/issues/217
https://github.com/electron-userland/electron-packager/issues/652
https://github.com/SimulatedGREG/electron-vue/issues/204

This module is pretty simple. One thing to note is that it downloads an ngrok binary during postinstall, and saves it to node_modules/ngrok/bin/ folder. Then it spawns the process with this binary to run tunnels. Maybe check if posinstall downloads or spawning processes are fine with electron packages.

**Comment by cvalenzuela** [comment]
thanks for the reply!

It seems it has something to do with the spawning process. Here a the error I get on triggering ngrok  from the production app:
```
ReactErrorUtils.js:50 Uncaught Error: spawn ENOTDIR
    at exports._errnoException (util.js:1050)
    at ChildProcess.spawn (internal/child_process.js:319)
    at exports.spawn (child_process.js:390)
    at runNgrok (/Users/cristobalvalenzuela/dropbox/cvalenzuelab/github/carbon/release/mac/Carbon.app/Contents/Resou…:108)
    at run (/Users/cristobalvalenzuela/dropbox/cvalenzuelab/github/carbon/release/mac/Carbon.app/Contents/Resou…:43)
    at /Users/cristobalvalenzuela/dropbox/cvalenzuelab/github/carbon/release/mac/Carbon.app/Contents/Resou…:54
    at lock (/Users/cristobalvalenzuela/dropbox/cvalenzuelab/github/carbon/release/mac/Carbon.app/Contents/Resou…:72)
    at EventEmitter.connect (/Users/cristobalvalenzuela/dropbox/cvalenzuelab/github/carbon/release/mac/Carbon.app/Contents/Resou…:37)
    at makeWorldPublic (Toolbar.js:116)
    at Object.t (ReactErrorUtils.js:25)
```

The `node_modules/ngrok/bin/` is copied into the final app.

ideas? I'm not sure how to debug this

**Comment by cvalenzuela** [comment]
So I figure this out:

When using electron, ngrok get's copied to `app.asar.unpacked` instead of to `app.asar` so in
[this line](https://github.com/bubenshchykov/ngrok/blob/master/index.js#L111):

```javascript
ngrok = spawn(
		bin,
		start,
		{cwd: __dirname + '/bin'});
```
`__dirname` refers to `../app.asar/bin` instead of `../app.asar.unpacked/bin` which triggers the error. I managed to solve it by adding this quick fix line to the ngrok package:

```
{cwd: __dirname.replace('app.asar', 'app.asar.unpacked') + '/bin'});
```

I'm not sure if this is the expected behaviour. I'm leaving this open in case you want to comment, but I guess this can be marked as resolved

thanks

**Comment by bubenshchykov** [comment]
Happy to see you solved it, great job!

I think we have two options two make it work for all - either to somehow
detect electron environment and substitute the path for binary (magic)  OR
to introduce a custom path option like binPath (for .connect method) or
NGROK_BIN_PATH global env var. Plus little readme section for electron
folks :)

What would you prefer? Feel free to submit PR! ;)

**Comment by cvalenzuela** [comment]
I implemented something similar to the second option. 
Let me refactor and I'll send a PR!

**Comment by bubenshchykov** [comment]
hi @cvalenzuela, let me know if you need help with PR ;)

**Comment by funnymail9999** [comment]
ngrok not working in termux android

**Comment by cvalenzuela** [comment]
thanks, @bubenshchykov. I just finished a hectic week. I have it implemented, just needs some clean up, will send the PR this week!

**Comment by bubenshchykov** [comment]
@cvalenzuela thanks for PR! I renamed this option to binPathReplacer and pushed to npm

**Comment by cvalenzuela** [comment]
awesome, thanks!
