### ISSUE TITLE
Callback function if connection is dropped or ngrok URL changed

### ISSUE THREAD

**Issue by shankqr** [bubenshchykov/ngrok#114]
Hi, when my nodejs app is disconnected from the internet for about a minute, the ngrok tunnel is dropped and how do I know this is happening so that I can reconnect with ngrok with await ngrok.connect()

Is there a Callback function if connection is dropped or ngrok URL changed?

**Comment by bubenshchykov** [comment]
hi, this case is not handled at the moment
the easiest would be to add onClose option ```const url = await ngrok.connect({port, onClose})```, and handle more stdout messages like in this fork https://github.com/expo/ngrok/blob/master/index.js#L107
