### ISSUE TITLE
Connection Timeout Error While Installing In Windows 10

### ISSUE THREAD

**Issue by mjangir** [bubenshchykov/ngrok#116]
When I'm trying to install ngrok with `npm install --save-dev ngrok` the following error is occuring in windows 10:

```
ngrok - install failed { Error: connect ETIMEDOUT 54.243.137.45:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '54.243.137.45',
  port: 443 }
```

and obviously the ip changes every time it retries. I'm sure it is somewhat related to TCP timeout configuration but shouldn't it work with the default windows settings.

**Comment by bubenshchykov** [comment]
I have never tested it on windows actually. Is it a permanent problem?

**Comment by mjangir** [comment]
I don't know whether it is permanent or temporary but one thing I would like to mention is, there is a proxy IP we always use in our computers here. for making the requests from node cmd, I had to set the npm config http-proxy with that IP but do we need to set anything for tcp connections also?

Its just a help requested not an issue with ngrok package probably.

**Comment by thisdavej** [comment]
I tested the following on my Windows 10 machine and it worked:

```
npm install --save-dev ngrok
```

Perhaps your proxy server is getting in the way. As one option, if permitted by your company, you could carry out the above command outside of your corporate network and then copy the `node_modules` folder back into your network.  Be prepared that the proxy server might get in the way when you invoke `ngrok` in your node code too.

As another option, you could download and unzip the ngrok Windows bin file from [here](https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip) (this is the same source used by the ngrok npm package) and copy it into `node_modules\ngrok\bin`, assuming this folder structure was created when running the above command.

**Comment by bubenshchykov** [comment]
@mjangir do you need more help on this?

**Comment by martinoss** [comment]
I've got the same problem on windows. ngrok is being installed as part of office fabric.
Tried the NGROK_CDN_URL workaround but it did not help. Creating the structure manually is not an option for me too, because rushjs used by fabric removes that folder before reinstalling.

**Comment by bubenshchykov** [comment]
@martinoss what problem did you encounter when trying NGROK_CDN_URL?
the wait it works: 
you download ngrok binary yourself and host it somewhere
you set NGROK_CDN_URL and NGROK_CDN_PATH (if needed) in your env vars before installing ngrok

Ngrok will then use the binary you provided
https://github.com/bubenshchykov/ngrok/blob/master/postinstall.js#L29

**Comment by martinoss** [comment]
@bubenshchykov Initially, I thought the specific url is blocked by the proxy, thats why I tried hosting it by myself, but I'm getting the same error with an alternate url.
I believe it has to do with 'request' (used to download the file) not configured to use a proxy. 
The corporate proxy requires NTLM authentication, so I'm forced to configure tools like git, npm, nvm, yarn, to use a local proxy (fiddler) that can forward the request with NTLM authentication to the corporate proxy.

I suggest to introduce an environment variable NGROK_PROXY_URL that is respected for downloading the binary.

**Comment by bubenshchykov** [comment]
@martinoss thanks for the detailed explanation. I'm not good at proxy things, but my idea was to host ngrok binary before the proxy wall, in a local machine or so. Then "request" won't hit the proxy at all. Not sure about that though :)

Anyway, adding support for proxies is a perfect idea. Actually, request module respects HTTP_PROXY and HTTPS_PROXY evn vars already, so you can just use them.
https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables

**Comment by martinoss** [comment]
@bubenshchykov Thats true HTTP_PROXY does it 👍. I remember this variable was required by bower and other tools too in the past...

**Comment by bubenshchykov** [comment]
Cool, I've added it to readme and closing the issue. Thanks for reporting!
