### ISSUE TITLE
Using ngrok as HTTP proxy server

### ISSUE THREAD

**Issue by ballsac** [bubenshchykov/ngrok#119]
Hello, I am trying to use ngrok as a HTTP proxy server similarly to this user's issue:
https://github.com/inconshreveable/ngrok/issues/379

In that post, a user says:

> ngrok will not send through forward proxy requests (just as you wouldn't expect haproxy or nginx to do that either). you can do it with a TCP tunnel though:
> 
> ngrok tcp 8888

How can I utilize that TCP tunnel to proxy HTTP requests on Windows? Do I need a separate program to do so? Is there a chrome extension or something that I can use to setup a connection to use the tunnel, etc?

Sorry for the noob question, but I would appreciate any help.

**Comment by bubenshchykov** [comment]
hi, sorry for a late response, but what exactly are trying to build?

**Comment by ballsac** [comment]
Thanks for your response.

I am trying to use a machine that is behind a carrier-grade NAT to proxy HTTP requests for other machines. Basically we have a site that IP bans addresses, so we want to use this machine to obtain new IPs which we would then like to use to proxy HTTP requests from other machines.

Hopefully this makes sense, if not please let me know. Also, if you can think of another way to build this, please let me know. Thanks for any help you can offer, I really appreciate it.

**Comment by bubenshchykov** [comment]
ahh, I'm not really good at NAT and proxy things
I think the best guy to ask for advise is @inconshreveable :)

**Comment by inconshreveable** [comment]
try starting ngrok in tcp mode pointing at an http proxy. e.g. run `ngrok tcp 8888` and then on port 8888 you'll need to run an http proxy server. or you can just run multiple ngrok tunnels, each one pointing at an internal service you want to expose

**Comment by ballsac** [comment]
Thank you both for your help.

I installed [CCProxy 8.0](http://www.cproxy.com), a Windows Proxy server, and configured it to bind to `port 8888` as suggested:
![ccproxy](https://user-images.githubusercontent.com/39440090/41112656-9304e8f6-6a4d-11e8-8221-27ea18c9f3e2.jpg)

I then ran ngrok in TCP mode pointing at `port 8888` using the command `ngrok.exe tcp 8888`:
![ngrok](https://user-images.githubusercontent.com/39440090/41112728-c8aa78fe-6a4d-11e8-8859-a9217ea881ba.jpg)

I then configured a chrome proxy extension to point at the ngrok address:
![proxy](https://user-images.githubusercontent.com/39440090/41112793-e03aa91c-6a4d-11e8-8f91-57bf2a12d4a7.jpg)

When I try to use these settings I am unable to bring up any web page successfully:
![internet](https://user-images.githubusercontent.com/39440090/41112972-6a49ad6a-6a4e-11e8-9d8e-e55cb5ceafb4.jpg)

What am I doing wrong?

**Comment by ballsac** [comment]
As a side note, if I set up a web server on port 80 and run ngrok with `ngrok.exe http 80` everything works perfectly.

**Comment by ballsac** [comment]
RIP

**Comment by bubenshchykov** [comment]
sorry @ballsac , i don't have an answer for you
inconshreveable seems to be busy too
try asking your question on stackoverflow maybe?

**Comment by 141801** [comment]
> Thanks for your response.
> 
> I am trying to use a machine that is behind a carrier-grade NAT to proxy HTTP requests for other machines. Basically we have a site that IP bans addresses, so we want to use this machine to obtain new IPs which we would then like to use to proxy HTTP requests from other machines.
> 
> Hopefully this makes sense, if not please let me know. Also, if you can think of another way to build this, please let me know. Thanks for any help you can offer, I really appreciate it.

Hello, The same question with you ,could you tell me how did you save it

I  want to use ngrok to expose my http-proxy server  in the internal net

**Comment by sqqihao** [comment]
> ngrok in TCP mode pointing at `port 8888` using the command `ngrok.exe tcp`

follow you , same problem....

**Comment by mAmged** [comment]
+1

**Comment by marcquesmouton** [comment]
Hello guys, i was struggeling with same issue with ccproxy. been at it since yesterday, but i am now using squid-cache instead.. 
use tcp for squid-cache... 

regards

**Comment by Hasan-Uddin** [comment]
as I know proxy uses HTTP protocol so it supposes to receive and respond through HTTP... I could be wrong
