### ISSUE TITLE
(non-global) installation failure - Ubuntu 18.04, node 10.9.0, npm 6.2.0

### ISSUE THREAD

**Issue by pkra** [bubenshchykov/ngrok#123]
The readme indicates that `npm i ngrok` should work ok while global installs requires sudo and unsafe-perms on Linux.

However, on Ubuntu 18.04, node 10.9.0, npm 6.2.0, `npm i ngrok` just hangs for me. 

When I clone the repor and run `npm i`, it installs but the npm security audit indicates 3 security issues. Running `npm audit fix` then hangs, so it looks like it's a newer version of a dependency that is breaking installation.

Has anyone run into this and found a workaround?

**Comment by bubenshchykov** [comment]
hi, thanks for reporting
never run into it, I'll mimic your environment and try to reproduce nearest days

**Comment by pkra** [comment]
Hm... `npm i` is working for me now and cloning, `npm i && npm audit fix` as well, so this may have been an issue on my end or something upstream was inadvertently fixed.

Sorry for the noise!
