### ISSUE TITLE
Ngrok not launching

### ISSUE THREAD

**Issue by stevemk14ebr** [bubenshchykov/ngrok#130]
On windows if you install this package the ngrok exe in the /bin folder doesn't have an exe extension. This causes the launch to fail to find the file and npm install to fail. Renaming this to .exe also doesn't fix it, since the ngrok exe is 1 year old it though it launches it is either too old or corrupt somehow. I suggest downloading the exe from the ngrok website in your install script and then verifying the hash of that file everytime before launch (please). The ngrok exe is in /node_modules/ngrok/bin/

**Comment by stevemk14ebr** [comment]
#67

**Comment by bubenshchykov** [comment]
hi, thanks for the detailed report! I will close this one in favor of #67

**Comment by iDRAGOO** [comment]
for those ngrok not launching  go to settings in windows 10 then network and internet settings then go to properties of your wifi connction and set network profile to public i hope this helps and sorry for my bad english
