### ISSUE TITLE
Possible error with Ngrok: failed MSpanList_Insert

### ISSUE THREAD

**Issue by gfcf14** [bubenshchykov/ngrok#132]
Hi. I'm writing this problem here as I was suggested the problem I've been having may have to do with Ngrok.

I am attempting to complete the Confluence Multi-page Blueprint tutorial (https://developer.atlassian.com/cloud/confluence/multi-page-blueprints-with-confluence-connect/) and as I completed all the steps up to **Host and install your app** I attempted to run the project with npm start, I got the following error:

<img width="499" alt="error" src="https://user-images.githubusercontent.com/716412/52063355-7904c080-2540-11e9-8b9e-9386eaa754bf.png">

The error **Failed MSpanList_Insert** seems to originate from `node_modules/ngrok/index.js:100:13`. I had posted my question [here](https://community.developer.atlassian.com/t/failed-to-establish-local-tunnel-on-multi-page-blueprints-with-confluence-connect/26693) and I was suggested that either I don't have ngrok installed, but that doesn't seem to be the case, or that I have a network restriction, but I am doing this tutorial on a mac for which I have admin rights. Is it possible that I am not following a step to use ngrok correctly? Please let me know, and thanks in advance.

**Comment by bubenshchykov** [comment]
hi, there are no special installation steps needed if you add ngrok to your package.json and require it from code

node_modules/ngrok/index.js:100:13 - line 100 does not even exist in index.js, so I suggest updating to the latest ngrok version first :)

**Comment by gfcf14** [comment]
I do have ngrok installed and updated, but in the end this wasn't an issue with ngrok, rather that atlassian/confluence's repo for this tutorial is using outdated libraries. Once this isssue is fixed, can I post a link with the solution for it here? This problem seems to be rather obscure and a few people have been asking about it for months and no solution has come up
