### ISSUE TITLE
[SUGGESTION] Add more details to errors

### ISSUE THREAD

**Issue by hypeofpipe** [bubenshchykov/ngrok#133]
Hello!

Today I had a problem with ngrok, and it was `failed to start tunnel`. So I was investigating the problem for hours, until didn't try `ngrok` at terminal and it finds out that 
```
Tunnel session failed: 

Your account 'BLABLABLA' is limited to 3 simultaneous ngrok client sessions.

Active ngrok client sessions in region 'us':
  - XXX (XXX.XXX.XXX.XXX)
  - XXX (XXX.XXX.XXX.XXX)
  - XXX (XXX.XXX.XXX.XXX)

ERR_NGROK_108
```

It would be better if we can just return the same error, or the main reason - too many active client sessions instead of vague `failed to start tunnel`.

**Comment by bubenshchykov** [comment]
hi, thanks for reporting that, great suggestion!
I'm not currently contributing to this module but will be happy to review and merge the PR

**Comment by bubenshchykov** [comment]
wanted to improve the error handling... but found out that current error is detailed enough
```
const ngrok = require('ngrok');
const error = await Promise.all([
	ngrok.connect(),
	ngrok.connect(),
	ngrok.connect(),
]).catch(ex => ex);

console.log(error);

// gives
{ error_code: 103,
  status_code: 502,
  msg: 'failed to start tunnel',
  details: 
   { err: 'Your account may not run more than 2 tunnels over a single ngrok client session.\nThe tunnels already running on this session are:\n[https://3ff62f8a.ngrok.io https://544c5b70.ngrok.io]\n\n\nERR_NGROK_324\n' } }
```

How can it be any better? =)
