### ISSUE TITLE
ngrok failed to create tunnel in Travis

### ISSUE THREAD

**Issue by lojzatran** [bubenshchykov/ngrok#139]
Since today, I suddenly have a problem with creating new tunnels in ngrok in Travis CI:
```
Error: the object {
  "details": {
    "err": {
      "Field": "addr"
      "Offset": 27
      "Struct": "HTTPTunnel"
      "Type": {}
      "Value": "number"
    }
  }
  "msg": "failed to deserialize request parameter"
  "status_code": 400
}
```
When I run the same code in my local machine, everything works just fine.

It seems like this repo also has [the same problem](https://travis-ci.org/bubenshchykov/ngrok/jobs/502571514). Any idea what is the reason and how to fix it? Thanks.

**Comment by lojzatran** [comment]
I did some testing in Travis debug mode and when I run this in the Travis machine, it works fine:
```
npm install ngrok -g
ngrok http 8080
```
but when I run this in Node REPL, it throws error like above:
```
const ngrok = require('ngrok');
(async function() {
  const url = await ngrok.connect();
})();
```

**Comment by miguelduarte42** [comment]
I'm seeing this in 3.1.1, which I have been using for some time now without any issues

**Comment by tbell511** [comment]
I am having the same issue.
```
{ status_code: 400,
  msg: 'failed to deserialize request parameter',
  details:
   { err:
      { Value: 'number',
        Type: {},
        Offset: 27,
        Struct: 'HTTPTunnel',
        Field: 'addr' } } }
```

Works fine on my mac though.

**Comment by inconshreveable** [comment]
ngrok pushed a new version of the ngrok client which is certainly the source of this issue. we're digging into it right now

**Comment by inconshreveable** [comment]
We've released a new version of the ngrok client, 2.3.13 that should solve this issue. Can you confirm?

**Comment by tbell511** [comment]
@inconshreveable It's working! Thanks for the update and quick fix!

**Comment by lojzatran** [comment]
Works again, thank you!
