### ISSUE TITLE
Can't install without request cafile (postinstall fails).

### ISSUE THREAD

**Issue by BuckAMayzing** [bubenshchykov/ngrok#142]
Hi folks, I'm having issues to get this to install properly due to the postinstall script. Here's my error. I'm working behind a corporate proxy/firewall (security isn't my strong suit, so I don't know all the moving parts here).

```
ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip
ngrok - error downloading binary { Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1051:34)
    at TLSSocket.emit (events.js:189:13)
    at TLSSocket._finishInit (_tls_wrap.js:633:8) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }
```

I pulled down the repo and was able to get this to work if I changed the get in the post install to the following:

```
const downloadStream = request
        .get({
            url: cdnUrl,
            ca: fs.readFileSync(path.resolve("path/to/my/cert/file.pem")),
        })
```

Are there any supported workarounds? Have you run into this before?

**Comment by bubenshchykov** [comment]
hey, a possible workaround is to host binary yourself and specify it in env var NGROK_CDN_URL / NGROK_CDN_PATH. postinstall.js will then skip the download from equinox. please, check the source code for more details.

Or you can have binary locally and introduce NGROK_BINARY_PATH var

Or you can add NGROK_SKIP_DOWNLOAD var and use "binPath" option that already exists https://github.com/bubenshchykov/ngrok#options

**Comment by bubenshchykov** [comment]
also, binary download happens with "request" module
and request module respects few related options that might help you
https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables

**Comment by BuckAMayzing** [comment]
Gotcha. Thanks Alex. I did see those environment variables, but was looking for something that would allow me to download the real binary to allow for potential ngrok updates in the future without the need for me to manually update.

Would you have any objections to me putting out a PR that will let modify the request call to use the CA file specified in .npmrc or an environment variable (the code above, but conditional)? I'm in favor of the .npmrc route since it's already a required step to get npm and yarn to work, but the environment variable fits with the current design of the project. 

I'm trying to get my project to "just work" as much as possible for the other team members.

**Comment by bubenshchykov** [comment]
absolutely! you are more than welcome to submit the PR, it's great to have an option to use CA file

some people solved a similar problem just by using "request" module options
https://github.com/bubenshchykov/ngrok/issues/116#issuecomment-400829039

**Comment by BuckAMayzing** [comment]
I will do this during the week. I wasn't able to use the proxy method. Thanks!

**Comment by BuckAMayzing** [comment]
I forgot to associate #143 with this. Apologies. I will close the issue now.

**Comment by bubenshchykov** [comment]
Published to npm: https://www.npmjs.com/package/ngrok/v/3.2.0
Was a pleasure to collaborate with you on this. Great job @BuckAMayzing !

**Comment by BuckAMayzing** [comment]
Same to you, Alex! Thanks!

**Comment by aksridhar** [comment]
Hey Alex - I know this is a old thread. I am having issues installing ngrok with npm due to firewall restrictions. I tried setting the environment variables in .npmrc file as well in .yml file for the Custom path for the binary but somehow 3.4.0 seems to be ignoring this. Can you provide more insight on how to get this thing point to a specific path. Appreciate your help.
