### ISSUE TITLE
I seem to get socket hangups very often when starting my ngrok.

### ISSUE THREAD

**Issue by TiborMalmo** [bubenshchykov/ngrok#145]
Hello! When I try to connect to ngrok using your package I seem to often get socket hangups. I get error messages like this:
`2019-06-28T11:05:27+0200 <error> ngrok-connector.js:29 (ngrok.connect.catch) Failed to connect to subdomain 'tibor-refined-general' { Error: socket hang up
   at createHangUpError (_http_client.js:323:15)
   at Socket.socketOnEnd (_http_client.js:426:23)
   at Socket.emit (events.js:194:15)
   at Socket.EventEmitter.emit (domain.js:441:20)
   at endReadableNT (_stream_readable.js:1125:12)
   at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' }`

it happens probably 50% of the time when I try to connect. Any idea what could be the cause of this? 

Thanks in advance :)

**Comment by bubenshchykov** [comment]
There might be a timing issue, because ngrok.connect first spawns the ngrok binary and then calls its internal api to start the tunnel. An easy fix is to a) add retries in your code b) or add retries to ngrok https://github.com/bubenshchykov/ngrok/blob/master/index.js#L57 =)

**Comment by TiborMalmo** [comment]
Thank you! I will try to fix it with that solution! :) 

Have a great day!
