### ISSUE TITLE
Expose the ngrok localhost URL to the caller

### ISSUE THREAD

**Issue by childish-sambino** [bubenshchykov/ngrok#152]
It would be nice if the calling application could retrieve the URL of the spawned ngrok process in case a user wants to view the explorer. It's _usually_ on port 4040, but not always.

**Comment by bubenshchykov** [comment]
hi @childish-sambino , it's already implemented
https://github.com/bubenshchykov/ngrok#inspector

**Comment by childish-sambino** [comment]
Yup, but how can I get the actual URL of the inspector to open in a web browser?

**Comment by bubenshchykov** [comment]
the host/port of ngrok web url is the same with api url
but you are right, it's impossible to extract it from "request" object of getAPI at the moment
re-opening
