### ISSUE TITLE
Add callback for all log events

### ISSUE THREAD

**Issue by childish-sambino** [bubenshchykov/ngrok#153]
The current callback option `onStatusChange` only alerts the caller when a connection is established or closed. Request a more generic `onLogEvent` callback that is invoked on each `stdout.data` event.

**Comment by bubenshchykov** [comment]
which stdout events are you interested in?

**Comment by childish-sambino** [comment]
All of them would be nice for debugging.

**Comment by bubenshchykov** [comment]
alternatively, we can optionally pipe stdout from ngrok to stdout of consumer
will it achieve the same goal for you?

**Comment by childish-sambino** [comment]
Regards,
Sam Harrison

**Comment by childish-sambino** [comment]
That would help. But it’s a less flexible implementation in case I later want to take some action based on state change or errors.

**Comment by bubenshchykov** [comment]
np, feel free to submit the pr that will meet your needs - i'll be quick to accept it
