### ISSUE TITLE
How can I get URL of existing connection?

### ISSUE THREAD

**Issue by techterbium** [bubenshchykov/ngrok#164]
Is there a way, where I can get the URL of the existing ngrok tunnel opened on a specific port?

Here is my use case: 
- I want to open a ngrok tunnel on the port, say 8080 before webpack starts.
- I want to access the URL of the tunnel at 8080, during webpack process, say, CopyWebpackPlugin.
- Also, I want to kill the process when the webpack-watch is closed.

Thanks in advance.

**Comment by bubenshchykov** [comment]
ngrok provides api to get urls of existing tunnels https://ngrok.com/docs#list-tunnels
it might be easier for you to use it directly

alternatively, you can start tunnel and run webpack in one node process
smth like
```javascript
const tunnelUrl = await ngrok.connect(8080);
runWebpack({ tunnelUrl }));
```
when webpack-watch exits it will also finish the main process, wchich will kill the ngrok process too

**Comment by techterbium** [comment]
Thank you @bubenshchykov. Although it doesn't solve my problem as is, I guess, you have given me a good lead here..
