### ISSUE TITLE
TS typings missing for `ngrok/download`

### ISSUE THREAD

**Issue by ledenis** [bubenshchykov/ngrok#166]
Following this PR https://github.com/bubenshchykov/ngrok/pull/160, it still misses typescript typings.

When trying to do `import * as downloadNgrok from 'ngrok/download';`:

```
Could not find a declaration file for module 'ngrok/download'. '/<path>/node_modules/ngrok/download.js' implicitly has an 'any' type.
  Try `npm install @types/ngrok` if it exists or add a new declaration (.d.ts) file containing `declare module 'ngrok/download';`ts(7016)
```

The suggested workaround works for now.

**Comment by philnash** [comment]
I don't think this is an issue any more. Please reopen if it still is.
