### ISSUE TITLE
Ngrok is not opening!!!!!!

### ISSUE THREAD

**Issue by CraftyArmy** [bubenshchykov/ngrok#180]
Every time I click on the program it closes and I have zero clues on how to fix it.  

edit: here a link to a video showcases the issue https://youtu.be/wTlDiJR_eXQ

**Comment by bubenshchykov** [comment]
hey, thanks for reporting!
try installing it from ngrok.com directly
this module is a wrapper around that binary, but it's tricky to get ```npm install -g``` working for windows

**Comment by MahbbRah** [comment]
Same issue here for me! even it's not running the tunnel hanging up when I'm doing like this `./ngrock http 80` just shows nothing and been there for hours!

**Comment by iDRAGOO** [comment]
for those ngrok not launching  go to settings in windows 10 then network and internet settings then go to properties of your wifi connction and set network profile to public i hope this helps and sorry for my bad english

**Comment by AnasterianSunstrider** [comment]
I have the same issue and Ive downloaded it from the official website.

**Comment by philnash** [comment]
If you have downloaded ngrok from ngrok.com and it doesn't work then we can't help you from this repo. This repo is about the Node.js module that can control the ngrok executable.

Instead, I recommend you get in touch with the ngrok team by chatting live or submitting a support ticket through [ngrok.com](https://ngrok.com). You can do this by visiting [ngrok.com](https://ngrok.com) and clicking "Ask a question" in the bottom right of your screen.

I am going to close this issue, if you are having trouble with this module, after installing it with `npm install ngrok`, then please open a new issue.

**Comment by haatochama** [comment]
in the windows file explorer directory, type cmd, then type ngrok, press enter
