### ISSUE TITLE
Ngrok tunnel not found 

### ISSUE THREAD

**Issue by jamesmiller9048** [bubenshchykov/ngrok#195]
I tried social pish inside local network it's okay but outside the network the following error is shown
tunnel url.ngrok.io not found
So I went to the terminal where I started ngrok and saw some errors 404 and 503
Same thing while trying to use it for metasploit inside the network it's okay but outside the network it's not working

**Comment by philnash** [comment]
Hey @jamesmiller9048, is this the same issue as #196?

**Comment by jamesmiller9048** [comment]
>no this is a different issue but if any one of them is solved then other will be solved I guess
Please help me

**Comment by Kamrulhasan12345** [comment]
I am also facing the same issue with ngrok (npm)
