### ISSUE TITLE
License info missing in the repo

### ISSUE THREAD

**Issue by amitsadaphule** [bubenshchykov/ngrok#208]
Hi, I could not find any license info or LICENSE file in the repo. [npmjs.org](https://www.npmjs.com/package/ngrok) mentions **BSD-2-Clause** in the license field for ngrok. I'd really appreciate if someone can confirm that or point me to the correct LICENSE file/documentation for this repo? Thanks in advance!

**Comment by philnash** [comment]
Hey @amitsadaphule, the license is listed in the [package.json](https://github.com/bubenshchykov/ngrok/blob/master/package.json#L34).

**Comment by amitsadaphule** [comment]
Thanks a lot @philnash!
