### ISSUE TITLE
ngrok over proxy

### ISSUE THREAD

**Issue by penguine** [bubenshchykov/ngrok#209]
when I test with command-line ngroks works fine over squid-proxy.
When I use you node project it works without proxy. When I use node with proxy the following bug returns:
/head><body id=ERR_CONNECT_FAIL>

<div id="titles">

<h1>ERROR</h1>

<h2>The requested URL could not be retrieved</h2>

</div>

<hr>

<div id="content">

<p>The following error was encountered while trying to retrieve the URL: <a href="http://127.0.0.1:4040/api/tunnels">http://127.0.0.1:4040/api/tunnels</a></p>

<blockquote id="error">

<p><b>Connection to 127.0.0.1 failed.</b></p>

</blockquote>

<p id="sysmsg">The system returned: <i>(111) Connection refused</i></p>

<p>The remote host or network may be down. Please try the request again.</p>

<p>Your cache administrator is <a href="mailto:webmaster?subject=CacheErrorInfo%20-%20ERR_CONNECT_FAIL&amp;body=CacheHost%3A%20wwwproxya%0D%0AErrPage%3A%20ERR_CONNECT_FAIL%0D%0AErr%3A%20(111)%20Connection%20refused%0D%0ATimeStamp%3A%20Mon,%2008%20Feb%202021%2012%3A22%3A04%20GMT%0D%0A%0D%0AClientIP%3A%20172.31.9.2%0D%0AServerIP%3A%20127.0.0.1%0D%0A%0D%0AHTTP%20Request%3A%0D%0APOST%20%2Fapi%2Ftunnels%20HTTP%2F1.1%0AHost%3A%20127.0.0.1%3A4040%0D%0AAccept%3A%20application%2Fjson%0D%0AContent-Type%3A%20application%2Fjson%0D%0AContent-Length%3A%20295%0D%0AVia%3A%201.1%20wwwproxygaia%20(squid%2F3.5.11)%0D%0ACache-Control%3A%20max-age%3D259200%0D%0AConnection%3A%20keep-alive%0D%0A%0D%0A%0D%0A">webmaster</a>.</p>

<br>

</div>

<hr>

<div id="footer">

<p>Generated Mon, 08 Feb 2021 12:22:04 GMT by wwwproxya (squid/3.5.11)</p>

</div>

</body></html>

it seems that the post request for the webinterface is send  to the proxy server instead of to the localhost

**Comment by philnash** [comment]
Hello, can you explain a bit more about the setup here and what to do to reproduce this error? How have you got Squid configured, how are you running ngrok with Node and how are you trying to access the dashboard to produce this error?

Thanks!

**Comment by penguine** [comment]
I think squid can not be the problem. I have tested several squid. On my test environment all squid rules are allowed.
you can reproduce the error, when you have a squid proxy and you configure the http_proxy for ngrok.connect.
The main traffice is going over proxy. But when ngrok try to call the local webinterface (localhost:4040) it fails.
When you set "web_addr: ip-adresss:port"  in ngrok.yml. (grok.connect doesn´t accept this option. You have to set it in ngrok.yml)
The API will be reached and ngrok works fine. But only on my squid with open rules. In production this workaround is not a solution and it will not work.
If you want I can send you my code. 
Thank you for your help!

**Comment by philnash** [comment]
It's not that I think squid is the problem, it's that I don't know how to setup and configure squid myself in order to reproduce this. Can you help?

**Comment by penguine** [comment]
With pleasure ;-)

If you have an ubuntu VM on your system you can install with:


```jsx
sudo apt install squid
```

in

```jsx
/etc/squid/squid.conf
```

your default proxy port is

```jsx
http_port 3128
```

you can set in development

```jsx
http_access allow all
```

restart

```jsx
sudo systemctl restart squid.service
```

you find the access log with:
```jsx
sudo tail -f /var/log/squid/access.log
```

**Comment by philnash** [comment]
Thank you! And then do you have an example of the code you're using that is failing too?

**Comment by penguine** [comment]
[ngrok.zip](https://github.com/bubenshchykov/ngrok/files/5980995/ngrok.zip)

**Comment by sammachin** [comment]
Hey @philnash Just spotted this issue, might be able to shed some light, are you only seeing it with ngrok >4.0.0 when you moved to got? I don't think this is a squid issue as such it would occur with any proxy. 

We saw simialr issues recently in node-red when we moved to got, there's a couple that seem related where we had to get upstream patches, the one  that I think  might be similar is  https://github.com/node-red/node-red/issues/3016 

hpagent has now fixed the issue in 0.1.2 so worth checking again with updated dependencies.

IN your case I think it should be ignoring the proxy env anyway as ngrok would be connecting to the API on localhost:4040

**Comment by penguine** [comment]
i think so too. it is probably due to the proxy implementation. I've seen this in other projects too, and if the module that sends the transfer via the proxy was changed, then it worked.
i will test with htis new version, thx

**Comment by penguine** [comment]
great, it works now.
THANK YOU

**Comment by philnash** [comment]
Thanks @sammachin. I'll look into increasing the version number of hpagent in the optional dependencies to account for this.
