### ISSUE TITLE
Promise not resolving when using "log_format: json"

### ISSUE THREAD

**Issue by uhagemann** [bubenshchykov/ngrok#210]
Hi, just stumbled this problem, since I had a ~/.ngrok2/ngrok.yml user config file with "log_format: json" in it and wondered why ngrok.connect would not resolve. Reason is that process.js assumes "logfmt" log format, which seems to be default, and gets stuck when confronted with json log entries.
Kind regards!

**Comment by philnash** [comment]
That's an interesting one. I'll have a look into sorting that soon.
