### ISSUE TITLE
Failed to open private leg

### ISSUE THREAD

**Issue by spiderlord202** [bubenshchykov/ngrok#212]
I keep getting this issue:
`t=2021-02-22T06:15:04+0000 lvl=warn msg="failed to open private leg" id=001c7f29800c typ=proxy` `privaddr=localhost:25565 err="dial tcp 127.0.0.1:25565: connect: connection refused"`

What does it mean? and how do I fix it?

Additional info:
I am hosting a Minecraft server and using ngrok to forward the port.

**Comment by philnash** [comment]
Are you getting that issue when you use the Node.js ngrok package or when you use the ngrok executable from ngrok.com?

**Comment by spiderlord202** [comment]
I am using the Node.js package. 
Code:
` Port = await ngrok.connect(`
 ` {`
` authtoken: "1ooYkVcrTifmLKOY63csrOjUEJP_3WkUW2VQeF89sHjpvf2FM",    configPath: './ngrok.yml', proto: ``'tcp', addr: 25565, `
  ` region: 'eu', onStatusChange: status => {`
   `    console.log(status)`
 `  }, `
	`onLogEvent: data => {`
      `if (SetUp){`
    `    console.log(data)`
    `  }     `          
  `   },`
`  }`
` )`
`.then(data => console.log(data)).catch(err => console.log(err))`

**Comment by philnash** [comment]
Any of the ideas/comments in [this issue help](https://github.com/thecoder-001/MineColab/issues/21)? It looks like they are trying to do something similar, though using a different ngrok library.

**Comment by spiderlord202** [comment]
So wait. Do I have to include the original server ip somewhere? If so where?

**Comment by spiderlord202** [comment]
One person said they fixed it by including the ip but besides that nothing else there helped me

**Comment by philnash** [comment]
I'm afraid I have no idea what you are actually doing with this Minecraft server, so I can't make suggestions without any more context. What IP address and port is your Minecraft server running on?

**Comment by spiderlord202** [comment]
The current ip/port is "0.tcp.eu.ngrok.io:14595". When I try and join it will either say connection refused(failed to open private leg) or connection timed out(join connections). Is there any info I can provide that can help you figure out how to solve this issue?

**Comment by philnash** [comment]
The more context you can give me about what you're doing, the more likely it is I can help. But I genuinely don't know what your setup is or what you're trying to achieve here. If you can tell me more about the server you are trying to open a connection to, I might be able to help.

**Comment by spiderlord202** [comment]
Well for starters the service I am hosting my server on is something.hosts free discord bot service with 2gs of RAM and node.js already installed. The reason I started using ngrok is because a person there affiliated with something.host said "You can host minecraft server in free discord hosting but you can't connect minecraft server over internet. Or ... Connect locally? [Port 2000 only works for http] You can try tcp port forwarding thing. Ex. Ngrok, portmap, etc." so I tried using this package.  
All code relating to the server:
`const { JavaCaller } = require('java-caller');`
`const java = new JavaCaller({`
`rootPath: __dirname,`
`jar: "Server.jar",`
`minimumJavaVersion: 10  `             
`});`
`const ngrok = require('ngrok');`
`async function Run(){`
`let process = await java.run(`
       `   [`
       `   '-Xms' + "125" + 'M',`
     `     '-Xmx' + "200" + 'M',`
        `  'nogui',`
         `  ], { `
       `     stdio: 'pipe',`
           ` detached: true`
      `     }`
         `  ); `
       ` console.log(process)`
`}`
`let Port = ""`
`async function Connect(){`
 ` Port = await ngrok.connect(`
  `{`
  ` authtoken: "(Censored)",    configPath: './ngrok.yml', proto: 'tcp', addr: 25565, `
  ` region: 'eu', onStatusChange: status => {`
     `  console.log(status)`
`   }, `
	`onLogEvent: data => {`
 `     if (SetUp){`
     `   console.log(data)`
 `     }        `       
   `  },`
`  }`
 `)`
`.then(data => console.log(data)).catch(err => console.log(err))`
`}`
`Connect().then(() => {`
  `Run()`
`})`

I used the package java-caller because java will be automatically installed if it was not found.
**you do not need to know what discord is or anything about it.**
I am using the latest version jar file from the website.

Server.properties:

#Minecraft server properties
#Tue Feb 23 07:16:34 UTC 2021
enable-jmx-monitoring=false
rcon.port=25575
level-seed=
gamemode=survival
enable-command-block=false
enable-query=false
generator-settings=
level-name=world
motd=A Minecraft Server
query.port=25565
pvp=true
generate-structures=true
difficulty=easy
network-compression-threshold=256
max-tick-time=60000
max-players=20
use-native-transport=true
online-mode=false
enable-status=true
allow-flight=false
broadcast-rcon-to-ops=true
view-distance=10
max-build-height=256
server-ip=
allow-nether=true
server-port=25565
enable-rcon=false
sync-chunk-writes=true
op-permission-level=4
prevent-proxy-connections=false
resource-pack=
entity-broadcast-range-percentage=100
rcon.password=
player-idle-timeout=0
force-gamemode=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
snooper-enabled=true
function-permission-level=2
level-type=default
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
resource-pack-sha1=
spawn-protection=16
max-world-size=29999984

**Comment by philnash** [comment]
You're starting up the Java program, the minecraft server, then trying to connect to it with ngrok. I wonder if it takes a while for the TCP server in the minecraft server to start up. Have you tried delaying starting ngrok?

Also, I'm not sure I feel good about helping you illicitly run a minecraft server for free on a server only meant for discord bots. I don't think this is an intentional use for ngrok, so I am going to close this issue.

**Comment by spiderlord202** [comment]
This was authorized by the same person affiliated with something.host that explained to me how I could do it. One of the managers did not say I was not allowed to do it, they were skeptical if it was possible to host a minecraft server on my service. I reserved a part of my service for my discord bot because the purpose of it was so people can use the bot to tp people to other servers (within the person getting teleported consent), like a place to grow your server. If you do not want to help me that's fine but can you at least tell me who can solve my issue?

**Comment by philnash** [comment]
Did you try delaying starting ngrok?

Did this person include instructions on how to achieve this?

**Comment by spiderlord202** [comment]
1. I tried that
2. Not exactly. He just recommended port forwarding but there have been some developments. 
Turns out I needed to open a port. I used express (a node module) to fix this but I still can't join the server and I am always getting: <h5>t=2021-02-27T06:04:26+0000 lvl=info msg="join connections" obj=join id=76a91e1e6afb l=127.0.0.1:25565 r=27.252.93.206:57275</h5>

I also got this log: 
<h5>
[06:47:11] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[06:47:16] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[06:47:16] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[06:47:16] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[06:47:16] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[06:47:16] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[06:47:16] [main/INFO]: Reloading ResourceManager: Default
<h5>

I would appreciate it if you could give me troubleshooting advice and reopen this issue.

**Comment by spiderlord202** [comment]
And here is the full ngrok log:
<h5>t=2021-02-27T07:06:09+0000 lvl=info msg="open config file" path=/home/container/node_modules/ngrok/bin/ngrok.yml err=nil
t=2021-02-27T07:06:09+0000 lvl=info msg="starting web service" obj=web addr=127.0.0.1:4040
t=2021-02-27T07:06:09+0000 lvl=info msg=start pg=/api/tunnels id=7beb93b317a8ef00
t=2021-02-27T07:06:09+0000 lvl=warn msg="ngrok is not yet ready to start tunnels" pg=/api/tunnels id=7beb93b317a8ef00 err="a successful ngrok tunnel session has not yet been established"
t=2021-02-27T07:06:09+0000 lvl=info msg=end pg=/api/tunnels id=7beb93b317a8ef00 status=503 dur=300.031µs
t=2021-02-27T07:06:09+0000 lvl=info msg=start pg=/api/tunnels id=4cde97ce161965a1
t=2021-02-27T07:06:09+0000 lvl=warn msg="ngrok is not yet ready to start tunnels" pg=/api/tunnels id=4cde97ce161965a1 err="a successful ngrok tunnel session has not yet been established"
t=2021-02-27T07:06:09+0000 lvl=info msg=end pg=/api/tunnels id=4cde97ce161965a1 status=503 dur=252.573µs
t=2021-02-27T07:06:09+0000 lvl=info msg=start pg=/api/tunnels id=ddd31c170bf0cc3e
t=2021-02-27T07:06:09+0000 lvl=warn msg="ngrok is not yet ready to start tunnels" pg=/api/tunnels id=ddd31c170bf0cc3e err="a successful ngrok tunnel session has not yet been established"
t=2021-02-27T07:06:09+0000 lvl=info msg=end pg=/api/tunnels id=ddd31c170bf0cc3e status=503 dur=291.345µs
t=2021-02-27T07:06:10+0000 lvl=info msg=start pg=/api/tunnels id=ea0a3230a47cda3b
t=2021-02-27T07:06:10+0000 lvl=warn msg="ngrok is not yet ready to start tunnels" pg=/api/tunnels id=ea0a3230a47cda3b err="a successful ngrok tunnel session has not yet been established"
t=2021-02-27T07:06:10+0000 lvl=info msg=end pg=/api/tunnels id=ea0a3230a47cda3b status=503 dur=224.102µs
t=2021-02-27T07:06:10+0000 lvl=info msg=start pg=/api/tunnels id=8410f748d8420989
t=2021-02-27T07:06:10+0000 lvl=warn msg="ngrok is not yet ready to start tunnels" pg=/api/tunnels id=8410f748d8420989 err="a successful ngrok tunnel session has not yet been established"
t=2021-02-27T07:06:10+0000 lvl=info msg=end pg=/api/tunnels id=8410f748d8420989 status=503 dur=232.127µs
t=2021-02-27T07:06:10+0000 lvl=info msg=start pg=/api/tunnels id=8331b44ef659c71e
t=2021-02-27T07:06:10+0000 lvl=info msg="tunnel session started" obj=tunnels.session
t=2021-02-27T07:06:10+0000 lvl=info msg="client session established" obj=csess id=60a230bcb409
connected
t=2021-02-27T07:06:10+0000 lvl=info msg="started tunnel" obj=tunnels name=74d734a1-ddf8-40d4-9406-a6ea49baad62 addr=//localhost:45308 url=tcp://0.tcp.au.ngrok.io:11056
t=2021-02-27T07:06:10+0000 lvl=info msg=end pg=/api/tunnels id=8331b44ef659c71e status=201 dur=291.826793ms</h5>

**Comment by philnash** [comment]
I think your problem lies with the way you are interacting with the Minecraft server at this point.

The second to last log from ngrok that you shared show that it started the tunnel successfully.

```
t=2021-02-27T07:06:10+0000 lvl=info msg="started tunnel" obj=tunnels name=74d734a1-ddf8-40d4-9406-a6ea49baad62 addr=//localhost:45308 url=tcp://0.tcp.au.ngrok.io:11056
```

The other logs you show seem to come from either your Node/Express server or the Minecraft server.

If I were you I would return to the person who suggested this method of setting up a Minecraft server and try to get more details out of them. This is beyond anything I can help with, especially as, as far as I can tell, ngrok is actually working properly.

**Comment by spiderlord202** [comment]
So your advice helped and I am almost finished. I am going to host a postgres db on something.host and make it public and now for this to work I need to kind of reverse it and tunnel an existing ngrok connection to localhost, this is why: https://node-postgres.com/features/connecting

**Comment by spiderlord202** [comment]
@philnash

**Comment by philnash** [comment]
ngrok does not, to my knowledge, work to tunnel to the `postgresql://` protocol and I've not used ngrok to tunnel to a PostgreSQL database before myself.  I guess that maybe a tcp connection would work, and for that, you'd need the port number your database is running on (typically, that is 5432).
