### ISSUE TITLE
Dev/daemon/sticky url mode

### ISSUE THREAD

**Issue by ryantheleach** [bubenshchykov/ngrok#215]
When quickly restarting an application during development, using NGrok as an NPM module has the distinct disadvantage of randomising your url each time, compared to running the binary directly.

It would be interesting if this library could provide an option to cache the NGrok process used, for X minutes after the application ends / restarts, as long as the configuration hasn't changed. (File or otherwise)

This would result in a saner development environment for developing webhook like applications, as you would only need to update the url with Twitch etc, each session, instead of each restart of the application.

If this is already possible / easily worked around using other tooling, then consider this a documentation request.

**Comment by philnash** [comment]
Would doing [something like this](https://gist.github.com/spalladino/45a6e54d7942ac0bad64dd54d7d12467) work for you? It uses [nodemon](https://nodemon.io/) and ngrok together to start a tunnel and watch for application changes and only restart the application and not ngrok.

**Comment by philnash** [comment]
I wrote up an up to date version of that script and how to use it. Check out [this blog post](https://philna.sh/blog/2021/03/15/restart-app-not-tunnel-ngrok-nodemon/) and let me know if it helps at all.

**Comment by ryantheleach** [comment]
Thanks!

**Comment by philnash** [comment]
@ryantheleach did that work for you? Can I close this issue?

**Comment by ryantheleach** [comment]
It will work, but I consider it a workaround compared to actually adding it as an option, or giving that blog post visibility in the readme / node page. It would be handy for more then just me.

**Comment by philnash** [comment]
@ryantheleach I'll happily link this from the README. I don't think this is something that we can build into this project though. Once you close a Node process, you don't want the processes within it to continue as zombies. So, when you close the parent process, the ngrok process will close and take the tunnel down.

Before using this project, I would just use the ngrok executable in another terminal tab, that way it's not tied to the process at all and will continue to live between application restarts.

Alternatively, if you are a VSCode user, check out my plugin that let's you [run ngrok from VSCode](https://marketplace.visualstudio.com/items?itemName=philnash.ngrok-for-vscode).

**Comment by philnash** [comment]
Updated the README to link the blog post: https://github.com/bubenshchykov/ngrok#using-with-nodemon
