### ISSUE TITLE
Upon install `npm install ngrok -g`

### ISSUE THREAD

**Issue by AshakaE** [bubenshchykov/ngrok#217]
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code EINTEGRITY
npm ERR! sha1-3zrhmayt+31ECqrgsp4icrJOxhk= integrity checksum failed when using sha1: wanted sha1-3zrhmayt+31ECqrgsp4icrJOxhk= but got sha512-8fgKh6QkMYF/Zge2SYHiZQoR8KRe2sl59Jtj8OuXKWusnT4kHJMJIVMbT+9/86zFF+w96ORgjmh37PBPjN38aQ== sha1-myXBGEEnMwIvDc/HLx58hwlvN8U=. (2711 bytes)

**Comment by philnash** [comment]
This is likely a mismatch between npm versions. There's a good blog post on what might be going on and how to fix it here: https://platformengineer.com/fix-npm-err-code-eintegrity-verification-failed-error/.

That deprecation notice will also go once I've released version 4 with [this PR](https://github.com/bubenshchykov/ngrok/pull/191) as part of it.

Let me know if you get it sorted.

**Comment by AshakaE** [comment]
Everything works fine, I believe the new npm update solved the issue
