### ISSUE TITLE
Running inside AWS Lambda

### ISSUE THREAD

**Issue by aecorredor** [bubenshchykov/ngrok#227]
I have a use case where I'm running synthetic monitors on a lambda that run every X minutes. The purpose of the lambda is to run a local http server, run ngrok to tunnel that server, and then run some integration tests that make sure that a webhook API works correctly.

I'm running into issues with running the package inside a lambda context because the binaries are of course not included in the build process of the lambda. I've tried using `downloadNgrok` inside the actual lambda code with no luck. The install usually fails with an error related to the stream having been destroyed or the zip file not existing in the directory.

I was wondering if there was any advice for achieving this or if anybody else had already done something similar? It seems like this is a common enough use case that somebody would already have found a solution. 

I'm guessing most people just packaged the binary inside the lambda at build time?

Thanks in advance.

**Comment by philnash** [comment]
Is there a reason that you don't put AWS API Gateway in front of your Lambda and make the request through there?

I would not have thought Lambda was a good environment for downloading and running a binary given the ephemeral file system.

**Comment by aecorredor** [comment]
The thing is I’d like to use ngrok inside the lambda not only to expose the local http server I’m running, but to actually use the API to list requests and make sure webhooks are called. I’m not sure how API Gateway would come into play there. Here’s kind of what the test looks like (all runs inside the same lambda):

1. Run an http server
2. Run ngrok to expose the above server
3. Call an external API that registers a webhook for X event. We pass the ngrok URL as the webhook endpoint.
4. Call some external API so event X gets triggered. 
5. List ngrok requests to assert that the webhook was correctly triggered after some time, i.e. make sure that the external API actually called the webhook after event X happened. 

This seem achievable and it’s actually working locally. The only thing Ieft is figuring out how to correctly include the ngrok binary in the lambda env.

How did you picture API gateway making things easier?

The other thing we had thought about was having the http server write to a dynamo table and then read from that table to make sure the webhook got called. But it’s basically doing what ngrok already gives us with a ton of overhead.

**Comment by philnash** [comment]
> How did you picture API gateway making things easier?

API Gateway is the AWS way to connect an incoming HTTP request to a Lambda. With a combination of API Gateway and Lambda you wouldn't need to run an HTTP server. You could just take the incoming requests from API Gateway to Lambda and then store them somehow. You may not need a database for the storage though, [you could log the requests and then verify them in Cloudwatch](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-logging.html) as an example.

Only running Lambda functions when they are called, rather than setting up a long running Lambda to wait for incoming requests seems more in line with how to use Lambda. It will also likely cost less to only respond to the incoming requests over running a long-running Lambda that is waiting for incoming requests over an ngrok connection.

I understand your setup is running correctly locally, but the execution pattern of a Lambda is quite different to a development laptop, so I wouldn't always rely on that as a measure. Having said that, I can try to help you debug whatever is going on.

> I'm running into issues with running the package inside a lambda context because the binaries are of course not included in the build process of the lambda. I've tried using `downloadNgrok` inside the actual lambda code with no luck. The install usually fails with an error related to the stream having been destroyed or the zip file not existing in the directory.

This module will attempt to download ngrok as part of its post install step. I guess that step isn't happening, so it makes sense to try to call `downloadNgrok` and download the binary yourself. If this is failing, can you share the error messages so we can try to debug properly? Also, do you know what the filesystem access is like within a Lambda function? Can you actually create files and execute them from within a Lambda?

Is there a packaging step when deploying to Lambda that you can use to download the correct binary and package it up for the deployment?

**Comment by aecorredor** [comment]
Thanks for the all that insight and for being willing to debug. We're considering those workarounds if the ngrok idea doesn't fly.

As far as debugging what's happening when calling `downloadNgrok`, these are some info/error logs:
1. `INFO	ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip`
2. `ngrok - error storing binary to local file [Error: ENOENT: no such file or directory, open '/var/task/bin/aHR0cHM6Ly9iaW4uZXF1aW5veC5pby9jLzRWbUR6QTdpYUhiL25ncm9rLXN0YWJsZS1saW51eC1hbWQ2NC56aXA=.zip']`
3. `ngrok - install failed, retrying`
4. `ngrok - error storing binary to local file Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed`

Then, if we try to connect to ngrok without the binary there we get `Error: spawn /var/task/bin/ngrok ENOENT`. So it seems it's trying to find ngrok in `/var/task/bin/ngrok`.

From the lambda FAQS (https://aws.amazon.com/lambda/faqs/) the only place where we can read/write storage inside a lambda is in the `/tmp` folder. So, I think that's the root of the issue. Maybe if we make `downloadNgrok` try to download and extract the binary into `/tmp` and then we use the already existing `binPath` property to make ngrok read the binary from `/tmp/bin/ngrok` things might work.

I'm going to actually try this by using `patch-package`.

**Comment by aecorredor** [comment]
That did it. I added some code to detect is we were on a lambda to change the `dir` accordingly. If it's something you'd like to add to the package I could make a PR, let me know. @philnash

**Comment by philnash** [comment]
I would be interested in a PR that let you choose the location of the download, if that's the sort of thing you have added!

Outside of improvements to this project, and I know you've got it working now, but I want to question one last time your use of ngrok and an http server within Lambda. Lambdas are functions that you can trigger with a number of methods, one of which being an HTTP request through API Gateway. Your use of a Lambda here appears to be to trigger the Lambda somehow, have it start up an HTTP server, download a binary that allows you to expose that server to external HTTP requests and then wait for requests to be made, triggering some further code within your Lambda. I am still pretty sure that using API Gateway and Lambda would cut out 90% of the difficulty here by having the webhooks you are testing trigger the Lambda via API Gateway directly.

**Comment by aecorredor** [comment]
> I would be interested in a PR that let you choose the location of the download, if that's the sort of thing you have added!
> 
> Outside of improvements to this project, and I know you've got it working now, but I want to question one last time your use of ngrok and an http server within Lambda. Lambdas are functions that you can trigger with a number of methods, one of which being an HTTP request through API Gateway. Your use of a Lambda here appears to be to trigger the Lambda somehow, have it start up an HTTP server, download a binary that allows you to expose that server to external HTTP requests and then wait for requests to be made, triggering some further code within your Lambda. I am still pretty sure that using API Gateway and Lambda would cut out 90% of the difficulty here by having the webhooks you are testing trigger the Lambda via API Gateway directly.

Gotcha. I didn't add exactly that but I could tweak the code so it's like that. 

Regarding the other point, you are right that the use case seems strange, and I do agree that using API Gateway so that webhooks trigger the lambda through it would also work. We started with this as an experiment to see if would work. We were just trying to keep that overhead of having the separate lambda + API gateway + some way of making sure it got called (like inspecting CloudWatch). We run our current lambda every X minutes as a monitor and wanted to try to keep things isolated to the test so we could easily manage it in one place. We might improve on this by creating a lambda layer with the ngrok binary instead of using `downloadNgrok`. 

Thanks again for being responsive on this! Will close issue for now.
