### ISSUE TITLE
Error catch causes error that hides the real error.

### ISSUE THREAD

**Issue by robblovell** [bubenshchykov/ngrok#229]
Also, there is a problem in the client code:

Here: 

```
 async request(method, path, options = {}) {
    try {
   ...
    } catch (error) {
      let clientError;
      try {
        const response = JSON.parse(error.response.body);
        clientError = new NgrokClientError(
          response.msg,
          error.response,
          response
        );
      } catch (e) {
        clientError = new NgrokClientError(
          error.response.body,
          error.response,
          error.response.body
        );
      }
      throw clientError;
    }
  }
```
Some errors don't have a response or a response.body and you "typeerror cannot read property 'body' of undefined", probably from the second catch... It would be better to just return the error. When doing so, you get a much more useful message that helped to debug the above missing await (ngrok is not yet ready to start tunnels):

in client.js
```
 async request(method, path, options = {}) {
    try {
   ...
    } catch (error) {
      let clientError;
      try {
        const response = JSON.parse(error.response);
        clientError = new NgrokClientError(
          response.msg,
          error.response,
          response
        );
      } 
```

**Comment by robblovell** [comment]
Perhaps there are changes in the replies from the NGROK api that are causing problems? Not sure. But it looks like there are some gremlins in here somewhere that cause the error handling to crash and the retry logic to fail.

Periodically, ECONNREFUSED 127.0.0.1:4040 is returned.

**Comment by gonzaloriestra** [comment]
I'm facing the same issue. I can reproduce it by updating my Ngrok token to a wrong one, and then I get the `Cannot read property 'body' of undefined`. But it doesn't happen every time, sometimes I get `NgrokClientError: failed to start tunnel` as expected.
