### ISSUE TITLE
Tunnel to non-localhost IP

### ISSUE THREAD

**Issue by wernight** [bubenshchykov/ngrok#23]
Ngrok supports [Forwarding to non-local services](https://ngrok.com/docs) but it seems that this package doesn't support that yet. Would be useful to support it.

**Comment by wernight** [comment]
Ok it's possible via:

    ngrok.connect({port: '192.168.0.1:80'}, function(...) {});

I'd add this to the README.

**Comment by bubenshchykov** [comment]
thx, this module supports basic ngrok features - and I'm trying to add more by any request

a nicer api for non-local tunnels could be 
```ngrok.connect({host: '192.168.0.1:80}', function(..){})```  or 
```ngrok.connect({ip: '192.168.0.1', port:80}, function(..){})``` etc  - but just updating readme is fine for now :)

**Comment by wernight** [comment]
Given the official CLI just takes that as first parameter, I'd suggest to mimic. You first line sounds good. For the full object version, given you pass it to the CLI, I'd be more inclined towards the second line, even though it's less clean. What's the argument name it `ngork --help` for that first argument?

**Comment by bubenshchykov** [comment]
good arguments, thx, agree!
