### ISSUE TITLE
NgrokClient.requestDetail missing Ngrok namespace in type definition

### ISSUE THREAD

**Issue by theaussiepom** [bubenshchykov/ngrok#232]
When consuming the ngrok package with typescript for Node 14, compiler fails with error:

```
node_modules/ngrok/ngrok.d.ts:217:40 - error TS2304: Cannot find name 'Request'.
217     requestDetail(id: string): Promise<Request>;
```

Like 217 of ngrok.d.ts should read:
`217     requestDetail(id: string): Promise<Ngrok.Request>;`

**Comment by theaussiepom** [comment]
See pull request: https://github.com/bubenshchykov/ngrok/pull/233

**Comment by philnash** [comment]
Thanks for raising and fixing this! I'll get this merged later today.

**Comment by theaussiepom** [comment]
Awesome, thanks Phil

**Comment by philnash** [comment]
This is deployed as of version 4.1.0. Thanks!
