### ISSUE TITLE
Node MaxListener Issue in Windows

### ISSUE THREAD

**Issue by agnibha92** [bubenshchykov/ngrok#239]
When using the ngrok tunnel programmatically using the node module.

`console - (node:19464) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)`

**Comment by agnibha92** [comment]
Instead of throwing a proper error, the module is breaking the application. In Linux, also a similar issue is observed whenever multiple applications are trying to open the tunnel.

**Comment by philnash** [comment]
I think this may be related to #179. Are you opening and killing the ngrok connection multiple times?

Also, this isn't an error, it's a warning. It shouldn't crash or break the application.

**Comment by agnibha92** [comment]
This is kind of a memory leak, and we're actually fixing it by improving maxListener to infinity, but this is not a good solution tbh.

**Comment by agnibha92** [comment]
Thanks for the crazy fast fix @philnash  :+1:
