### ISSUE TITLE
download is failing

### ISSUE THREAD

**Issue by vvo** [bubenshchykov/ngrok#24]
Receiving `ETIMEDOUT` while trying to use node-ngrok, seems like we cannot download it anymore.

**Comment by bubenshchykov** [comment]
shit, it's because ngrog 2.0 pre-release.. i'll take care of it asap and let u know. thx man!

**Comment by bubenshchykov** [comment]
@vvo download seems to be back to the previous speed, no timeouts - do u still have problem installing the module?

**Comment by bubenshchykov** [comment]
@vvo can't repro, closing the issue for now. I'll be able to help if problem happens again :)

**Comment by vvo** [comment]
Sorry, thanks a lot for fixing this, it works :)
