### ISSUE TITLE
When the NGROK process exits unexpectedly, the consumer of the package is not notified

### ISSUE THREAD

**Issue by theaussiepom** [bubenshchykov/ngrok#243]
When the ngrok tunnel closes, the consumer is notified by the "closed" status event. This is the happy path.
When the ngrok process closes unexpectedly, the consumer is not notified, and will be unaware that a tunnel no longer exists.

In process.js, I'm wondering if the following code should be altered from:
```
  ngrok.on("exit", () => {
    processPromise = null;
    activeProcess = null;
  });

```
to something like:
```
  ngrok.on("exit", () => {
    processPromise = null;
    activeProcess = null;
    opts.onTerminate();
  });
```

**Comment by theaussiepom** [comment]
Solution available in pull request https://github.com/bubenshchykov/ngrok/pull/244

**Comment by philnash** [comment]
This was fixed ages ago, why didn't I close this issue?!
