### ISSUE TITLE
TCP tunnel to 22, error Connection timed out

### ISSUE THREAD

**Issue by Zigecek** [bubenshchykov/ngrok#247]
Hi, I want to make that everytime the script is executed it just connects 22 to ngrok and save the url to the database, this works, but as I want to connect to the SSH, it says Connection timed out, I tried many different way to connect to it, but everything shows the same error, this is my code:

```
const ngrok = require("ngrok");
const mong = require("./utils/mongoose");
const Config = require("./utils/models/Config");

const main = async () => {
  mong.init();
  await ngrok.authtoken("1phgGZrYSAOqBK60Lt8bbli12qd_Q4vtEAJxdm1jCcBdHhkR");
  const url = await ngrok.connect({
    proto: "tcp",
    region: "eu",
    addr: 22,
    onStatusChange: statusChange,
  });
  Config.findOneAndUpdate(
    {
      number: 1,
    },
    {
      ngrokRpiSSH: url,
    },
    function (err) {
      if (err) {
        console.error(err);
        error.sendError(err);
        return;
      }
    }
  );
};

main();

function statusChange(status) {
  if (status == "closed") {
    console.warn("retrying to connect");
    main();
  }
}

```

**Comment by philnash** [comment]
Is it ngrok timing out, or the connection to whatever you have running on port 22? Does the ngrok dashboard (localhost:4040) show you anything more about the connection?

**Comment by Zigecek** [comment]
Sorry for late response, I just find out that my network had disabled some ports.
