### ISSUE TITLE
Does this package install the ngrok tool as well?

### ISSUE THREAD

**Issue by vfonic** [bubenshchykov/ngrok#249]
I already have ngrok installed and setup locally so it's difficult to test this.

I'm curious, if I have "ngrok" npm package (this package) in my `package.json` dependencies and I run (on CI or on another machine) `npm install`, will it automatically install the "ngrok" CLI tool as well or I need to first install "ngrok" tool manually and only then I can use this package?

Thanks!

**Comment by philnash** [comment]
This package will download the ngrok binary as part of its postinstall step. You do not need to install the ngrok binary yourself.

**Comment by vfonic** [comment]
Awesome! Thanks! 🚀
