### ISSUE TITLE
ngrok 2.0?

### ISSUE THREAD

**Issue by gavinengel** [bubenshchykov/ngrok#25]
When will the npm use ngrok 2?

**Comment by bubenshchykov** [comment]
right now in progress :) i think I'll push ngrok 2.0 today-tomor' with the same feature set today
and then will be slowly adding new 2.0 features. anything specific u expect?

**Comment by gavinengel** [comment]
Cool.  I like the performance changes, so I was looking forward to the npm project being updated.  Thanks!

**Comment by bubenshchykov** [comment]
I'm waiting for another bugfix in ngrok shell, and then will publish master with 2.0 support for npm. Friday or so, sorry for the delay )

**Comment by gavinengel** [comment]
I guess what I'm most interested in is the custom domains.  It seems to me that ngrok version 1.x uses domain ngrok.com, whereas version 2.x uses ngrok.io.

**Comment by bubenshchykov** [comment]
module with ngrok 2.x is still not published to npm, waits for a fix pls. could u pls explain what's wrong with ngrok.io tunnels ?

**Comment by gavinengel** [comment]
I'm just confused with the whole setup at this point :-(  I'm trying to use a custom/reserved domain: helloworld.engeldev.com.  Would you recommend I use ngrok 1 or 2?

**Comment by bubenshchykov** [comment]
For now please use ngrok 1, as ngrok 2 is not yet released
ngrok 2 will have the same api, no breaking changes

all u need is
```js
connect({
  authoken: 'sdfsdf', // required for subdomain use
  subdomain: 'gavinengel',
  port: 8080
}, cb)
```

**Comment by gavinengel** [comment]
OK I'll use ngrok 1 for the next couple weeks.  Thanks!
