### ISSUE TITLE
Doesn't work with Node.js v17.0.1

### ISSUE THREAD

**Issue by n0bisuke** [bubenshchykov/ngrok#254]
```
$ ngrok http 3000
[1]    1301 killed     ngrok http 3000
```

Is there anyone with a similar phenomenon?

Here is a memo for myself.

> https://zenn.dev/n0bisuke/scraps/e24fc3651b350c

**Comment by nsainaney** [comment]
@philnash - just submitted a PR for this. Would appreciate it if it could get reviewed, merged, and published. Thank you

**Comment by nsainaney** [comment]
Between the PR and https://github.com/nodejs/node/issues/40702, I have tested the package on Node 17 and everything seems to work now

**Comment by philnash** [comment]
Hey @nsainaney, sorry I haven't got to the PR yet. What is the relevance of nodejs/node#40702 to this though? I'm not sure I see a connection.

**Comment by nsainaney** [comment]
@philnash, we were using an axios based client that was initialized with `http://localhost:4040/`. You are not doing that so the nodejs is not relevant to your repo. You can disregard my comment. Sorry for any confusion.

**Comment by philnash** [comment]
Ha, ok. I'll get to the PR review later. Thanks!

**Comment by johnlindquist** [comment]
I just ran into this issue as well. Have you had a chance to look into the PR?

**Comment by KylChiang** [comment]
just try to download(https://ngrok.com/download) the M1 zip file and drop the ngrok.exec file into "/opt/homebrew/bin/", finally it works!

**Comment by 1xtr** [comment]
I have some issue on win10 and macos. I solved it with replacing bin files in node_modules with files from ngrok.com
i have lates node version

**Comment by Alynva** [comment]
I'm having the same issue. My `bin/ngrok` has this content:
> stub to allow npm symlink before postinstall starts

Looking that file here in the repo, looks like it's actually with the wrong version of it.

I don't think that should be the content of the file. Someone wiped the git history.

**Comment by philnash** [comment]
The fix for this has been released as part of version 4.3.0 on npm now.

**Comment by n0bisuke** [comment]
Thank you so much :)
