### ISSUE TITLE
uuid < 7 is deprecated for security reasons

### ISSUE THREAD

**Issue by BigZ** [bubenshchykov/ngrok#256]
we should upgrade uuid dependency to >= 7 
Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
if you agree, i can provide the PR
thanks for the great work on ngrok folks

**Comment by philnash** [comment]
UUID is only used to [generate a random name for a tunnel](https://github.com/bubenshchykov/ngrok/blob/7e225cb7e79a8311bb65f16a3a2f3017c4600b14/index.js#L27). The name allows you to refer to the tunnel in further API requests to the internal API. 

So, even if it is not as random as it needs to be for security purposes, I don't believe that makes it a security concern for this package.

However, I do believe in keeping dependencies up to date, so if you want to put together a PR for the upgrade I would happily review and merge it. Thanks!

**Comment by philnash** [comment]
This has now been fixed and published as part of version 4.3.0.
