### ISSUE TITLE
Checking if an account is free or paid

### ISSUE THREAD

**Issue by subhanahmed047** [bubenshchykov/ngrok#259]
Is there a way to determine programmatically if an account is paid or free? 

We're using ngrok js client API to start tunnels with our custom domains ( a feature that is only present for paid accounts), but we would like to add a fallback for someone who doesn't have a paid account and still want to use the app feature. Is there any way we could check the status of an account? via CLI, or js client.

**Comment by philnash** [comment]
There isn't an [API endpoint made available by the agent](https://ngrok.com/docs#client-api) to determine this, nor a [public API endpoint](https://ngrok.com/docs/api). Both the public and agent APIs return well defined errors though, so you should be able to find the error code from the [error list](https://ngrok.com/docs/errors) here and react accordingly when this client returns an error.

Does that help?

**Comment by subhanahmed047** [comment]
Thanks, I ended up with the following solution:

send a request to the [reserved domains api](https://ngrok.com/docs/api#reserved_domains). i.e.
```
curl \
-H "Authorization: Bearer {API_KEY}" \
-H "Content-Type: application/json" \
-H "Ngrok-Version: 2" \
-d '{"name":"myapp.mydomain.com","region":"us","certificate_id":"cert_1zlnghudbf2QxNkZNeaNSxnFQXy"}' \
https://api.ngrok.com/reserved_domains
```
If you were a user who belongs to the same paid account, you would have a `process.env.NGROK_API_KEY` available. In that case, the above request would throw the following error:
```
{"error_code":"ERR_NGROK_413","status_code":400,"msg":"This domain is already reserved for your account. Failed to reserve 'xxxxxxxxxxxxx.","details":{"operation_id":"xxxxxxxxxxxxx"}}%
```
If not, then you are not the person of interest and should get the free options. 

Although the above might serve my purpose, I'm not quite happy with the approach as errors are not usually cached, and intentionally getting an error to achieve this seems odd. I'm gonna park this until (if ever) there is a proper way of doing it.

**Comment by philnash** [comment]
I'm going to close this issue for now, since it's not something that this project can fix. You might find a better response taking it up with the ngrok team themselves. (Note, this repo is just the Node.js wrapper for the ngrok CLI and is not supported or maintained by the ngrok team.)

Thanks!
