### ISSUE TITLE
AttributeError: module 'pyngrok.ngrok' has no attribute 'connect' 

### ISSUE THREAD

**Issue by denicargit** [bubenshchykov/ngrok#269]
Need help

**Comment by philnash** [comment]
Are you working with the [python wrapper for ngrok](https://pypi.org/project/pyngrok/)? Because this is the repo for the Node.js wrapper. You can find the [docs for pyngrok here](https://pyngrok.readthedocs.io/en/latest/index.html).

**Comment by philnash** [comment]
I'm going to close this issue as it seems that it is an issue with [pyngrok](https://pypi.org/project/pyngrok/).
