### ISSUE TITLE
Wrong binary installation for Apple Silicon

### ISSUE THREAD

**Issue by gonzaloriestra** [bubenshchykov/ngrok#274]
When the platform is `darwinarm64` (Apple Silicon), it's installing the Ngrok binary for AMD, but there is one specific for ARM64: `darwin-arm64.zip`:

https://github.com/bubenshchykov/ngrok/blob/6a480109fedab6e6bc5d11a3384fb2858ab95c6e/download.js#L42

When Rosetta is present it works, but it's failing otherwise: `spawn Unknown system error -86`.

**Comment by philnash** [comment]
Just merged #223 which will handle this.
