### ISSUE TITLE
Module not found: Can't resolve 'http2'

### ISSUE THREAD

**Issue by avikalpg** [bubenshchykov/ngrok#276]
I get this error on importing the `ngrok` module into my file.

```
../node_modules/http2-wrapper/source/index.js
Module not found: Can't resolve 'http2' in 'C:\Users\avika\Documents\Work\Sustainable Innovation\Alokit\mentorship-website\node_modules\http2-wrapper\source'
```

My node version: v14.15.3

**Comment by philnash** [comment]
Seems like maybe an issue with npm installation? Have you tried removing your `node_modules` folder and installing again?

**Comment by philnash** [comment]
Hey @avikalpg, did you try removing your `node_modules` folder and installing again? Just hoping to either find out some more information or close this issue out. Thanks!

**Comment by avikalpg** [comment]
Hi @philnash,

Sorry I missed this notification. I will try this solution today and update this thread.

**Comment by philnash** [comment]
Thanks @avikalpg, let me know how it goes.
