### ISSUE TITLE
ERR_NGROK_6204 - Visit Site button on Splash Screen does not navigate to website 

### ISSUE THREAD

**Issue by tyschreiver** [bubenshchykov/ngrok#281]
For the last few months, I have been using ngrok to host a website. Starting a few days ago, when you navigate to the ngrok link, it shows a splash screen before navigating to my website. There is a "Visit Site" button, but clicking on it just refreshes the page. I have been unable to get past this screen.

https://user-images.githubusercontent.com/21366264/179310936-d7881548-9733-42e0-94ea-ee1c232c79a5.mov

Is this a bug, or does anyone have advice to get past this?

There are a couple of suggestions at the bottom of the screen, but I haven't been able to find any information about how to implement them. 
* `Set and send an [ngrok-skip-browser-warning] request header with any value.`
* `Or, set and send a custom/non-standard browser [User-Agent] request header.`

If someone knows how to implement either of those two suggestions, I would appreciate a little guidance

**Comment by philnash** [comment]
That seems like it's an issue with ngrok itself and not this project (the Node.js wrapper for ngrok).

That is weird that your page just refreshes, I would check if you were blocking cookies or storage on `ngrok.io` subdomains, as I assume that when the page says it should only appear once it drops a cookie to ensure that.

I'd suggest dropping into the [ngrok community on Slack](https://ngrok.com/slack) or hitting them up on [Twitter](https://twitter.com/ngrokHQ) or [LinkedIn](https://www.linkedin.com/company/ngrok) to see if you can get help with this. I don't think it's something we can solve in this JS wrapper, so I am going to close this issue.
