### ISSUE TITLE
Automatic setup for `ngrok tcp <IP> <PORT>`

### ISSUE THREAD

**Issue by Morsmalleo** [bubenshchykov/ngrok#283]
Hey guys, just wondering if it's possible to automatically setup a TCP tunnel through ngrok based on user IP & Port input on a *Web Panel* or possibly a `BrowserWindow` through electron?

**Comment by philnash** [comment]
You could certainly build something like that using this library. For example, I have built a VS Code extension that allows you to [start ngrok tunnels from within VS Code](https://marketplace.visualstudio.com/items?itemName=philnash.ngrok-for-vscode) (though it defaults to HTTP tunnels). The [source of the extension is here](https://github.com/philnash/ngrok-for-vscode) if you want to look.

**Comment by Morsmalleo** [comment]
> You could certainly build something like that using this library. For example, I have built a VS Code extension that allows you to [start ngrok tunnels from within VS Code](https://marketplace.visualstudio.com/items?itemName=philnash.ngrok-for-vscode) (though it defaults to HTTP tunnels). The [source of the extension is here](https://github.com/philnash/ngrok-for-vscode) if you want to look.

Thank you so much, I'll take a look now.

**Comment by Morsmalleo** [comment]
> You could certainly build something like that using this library. For example, I have built a VS Code extension that allows you to [start ngrok tunnels from within VS Code](https://marketplace.visualstudio.com/items?itemName=philnash.ngrok-for-vscode) (though it defaults to HTTP tunnels). The [source of the extension is here](https://github.com/philnash/ngrok-for-vscode) if you want to look.

Yep this is pretty much what I'm looking for thank you!
