### ISSUE TITLE
How to add ngrok-skip-browser-warning request header?

### ISSUE THREAD

**Issue by cademcniven** [bubenshchykov/ngrok#285]
So like others I get this screen when I try to connect:

![image](https://user-images.githubusercontent.com/17060136/181122537-90407c0b-084d-44c3-aef5-713bc433570b.png)

Unlike #281, my page doesn't refresh when I click the "visit site" button (it properly takes me to my page). However, for the life of me I can't figure out a way to set the header and get rid of that page. Any help would be appreciated.

**Comment by philnash** [comment]
You could use a browser extension [like this one](https://chrome.google.com/webstore/detail/header-editor/eningockdidmgiojffjmkdblpjocbhgh?hl=en). I've not used it, but it looks like it can add headers to browser requests, which is what you need.
