### ISSUE TITLE
ngrok not runnng 

### ISSUE THREAD

**Issue by Lordjecen** [bubenshchykov/ngrok#287]
i downloaded ngrok and installed it but it couldn't run on my system. it closed automatically while i was running it

**Comment by philnash** [comment]
Hey, did you download ngrok from ngrok.com? Or did you install via npm?

If you downloaded from ngrok.com, then we can't help you in this repo. This repo is just the Node.js wrapper for the ngrok executable. Please contact ngrok support for help there.

If you installed via npm then please share any errors you get when running ngrok from Node.js.

Thanks

**Comment by philnash** [comment]
Hey @Lordjecen, just following up on my questions. Please let me know how you downloaded ngrok, so we can either help or close this issue. Thanks!

**Comment by philnash** [comment]
Hey, I'm going to close this issue as there's been no response. Please feel free to reopen if you are still having trouble and can answer the questions above. Thanks!
