### ISSUE TITLE
Installation fails - Ngrock not in NPM registry

### ISSUE THREAD

**Issue by sshillyer** [bubenshchykov/ngrok#289]
Any variant of installing ngrock fails for me on Mac / PC, e.g.:
`npm install ngrock -g --unsafe-perm=true --allow-root`
`npm install ngrock -g`

Output:
```
npm install ngrock -g --unsafe-perm=true --allow-root
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/ngrock - Not found
npm ERR! 404
npm ERR! 404  'ngrock@*' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by philnash** [comment]
Good news, this is because of a typo. Try:

```
npm install ngrok -g
```

**Comment by sshillyer** [comment]
You are correct! I was on a false path. 

We're seeing an error during postinstall.js so I thought to try installing globally and saw this 404, apologies for the time waste. can open a separate issue if something comes up
