### ISSUE TITLE
Can't get callback from connect

### ISSUE THREAD

**Issue by SteveNewhouse** [bubenshchykov/ngrok#29]
Hello there--- I'm new to ngrok and struggling to get the connection set up properly.  Here's my connect call, the callback is never invoked and I get no error:

	ngrok.connect(config.ngrok, function(err, url) {
		console.log(err);
	});

Here's the config.ngrok object, note that even if I use a simpler connect call with no opts object, just a port, it still doesn't work:
	
	ngrok: {
		proto: 'http', 
		port: 8096,
		auth: 'hidden:hidden', // http basic authentication for tunnel
		authtoken: 'hidden, // your authtoken from ngrok.com
		bind_tls: 'true',
		web_addr: 4041
	}

Anyone know what might be going on?  I can set up a tunnel from bash, just not from node.js.

**Comment by bubenshchykov** [comment]
I guess you are using ngrok from npm, it still has old version 1.x and bind_tls is not supported yet
as well as web_addr. Please follow the readme here - it shows the right set of options supported
https://www.npmjs.com/package/ngrok

**Comment by jonathankeebler** [comment]
@bubenshchykov It still doesn't work with that config. 

@SteveNewhouse The only thing I could do to get it working was to delete ~/.ngrok and
```
ngrok.connect(8096, function(err, url) {
    console.log(err);
});

**Comment by SteveNewhouse** [comment]
It appeared to be related to the fact that I had generated auth tokens for
v2 and did not remove them when I went back to v1?

**Comment by bubenshchykov** [comment]
exactly, sorry for that. it was written on official ngrok site, that authtokens for v1 has nothing to do with v2 and vise versa. i hope i'll be able to push 2.0 soon to avoid all this confusion.
