### ISSUE TITLE
zsh: parse error near `}

### ISSUE THREAD

**Issue by Abdul-hash47** [bubenshchykov/ngrok#290]

**Comment by philnash** [comment]
Hello @Abdul-hash47, I think I might need a bit more detail than that. What did you do and how did you get that error? Anything you can share makes it easier to help you.

**Comment by hangshan-boop** [comment]
![Uploading IMG_20241215_202220.jpg…]()

**Comment by philnash** [comment]
Not sure what you're trying to say there @hangshan-boop.
