### ISSUE TITLE
Fully NodeJS solution with Tunnelmole?

### ISSUE THREAD

**Issue by robbie-cahill** [bubenshchykov/ngrok#300]
This project is a wrapper around `ngrok`, but `ngrok` is closed source and is starting to get expensive especially for commercial use.

I've just launched Tunnelmole, an open source solution which is built in TypeScript and runs with JavaScript code. I'm looking to integrate with some other open source projects.

Some advantages I can see of integrating Tunnelmole here would be:
- No need to fork a separate process. The Tunnelmole code compiles to JavaScript, so you could just call a simple async function to get the tunnel up and running
- The possibility of self hosting. The Tunnelmole service is also open source, so its possible to run your own server, but its not required as I have a hosted service available.

The client code is here: https://github.com/robbie-cahill/tunnelmole-client. It is MIT licensed and I could easily turn it into an `npm` module to include as a dependency.

I'd be willing to contribute the changes needed to both projects to do the integration which shouldn't be too much work, what do you think?

**Comment by philnash** [comment]
I think it would be useful to build an npm module so that Node users can use Tunnelmole, but I don't believe it would be useful to integrate that library into this one, which is specifically for using ngrok.

Nice work with Tunnelmole though, it's always good to have options in this space.
