### ISSUE TITLE
support free domain

### ISSUE THREAD

**Issue by igorovic** [bubenshchykov/ngrok#316]
We are allowed to one free domain. According to the documentation.

![image](https://github.com/bubenshchykov/ngrok/assets/758832/c073390c-4d22-4ea5-8067-61be6c8d8ef5)

I was not able to start ngrok with the free domain. 

Is this supported or planned to be  ?

**Comment by neonexus** [comment]
Check out the official NPM package for Ngrok (I've had zero issues with it):

[@ngrok/ngrok](https://npmjs.com/package/@ngrok/ngrok)
