### ISSUE TITLE
complains about set subdomain

### ISSUE THREAD

**Issue by fiws** [bubenshchykov/ngrok#34]
```
> ngrok.connect({addr: 3000, authtoken: process.env.TOKEN}, function(err){console.log(err)})
undefined
> [Error: {"error_code":103,"status_code":502,"msg":"failed to start tunnel","details":{"err":"Custom subdomains are only available for paid plans. Upgrade at https://dashboard.ngrok.com/billing/plan"}}]
```

even though I did not set any subdomain.

**Comment by bubenshchykov** [comment]
@fiws sorry for that, I'll see what I can do today. meanwhile u can use ngrok@0.1.99 - it uses ngrok 1 and doesn't require an authtoken at all

@inconshreveable I guess it's the same issue we discussed before. when making a tunnel through api requires a "name" as a tunnel ID, same time treats it as a custom subdomain and thus requires a paid subscription. Am I correct? Is name still required for api posts and acts as a tunnel ID?

**Comment by vvo** [comment]
Also seeing this as an issue

**Comment by abrkn** [comment]
:+1:

**Comment by sebpiq** [comment]
Same issue here :(

**Comment by lejeunerenard** [comment]
:+1:

**Comment by liabru** [comment]
+1

**Comment by henninghorn** [comment]
You can use ngrok-my-server:
- https://github.com/lightsofapollo/ngrok-my-server

That module works and it seems to be using this module - I'm not sure.

**Comment by fiws** [comment]
@henninghorn probably because it uses 0.1.x (`"ngrok": "~0.1.8"`)

**Comment by mlemainque** [comment]
We also have that problem :-1:

**Comment by spacedawwwg** [comment]
Same issue here. Reverted back to v1.x for the time being

**Comment by bubenshchykov** [comment]
@spacedawwwg you did right, it's also recommended in readme to use 0.1.x
the latest version on npm still awaits a critical fix from native go ngrok, @inconshreveable will let us know
sorry for inconveniences!

**Comment by BenjaminConant** [comment]
same issue ... followed the instructions on the ngrok npm module ...

```
var ngrok = require('ngrok');
ngrok.connect(9000, function (err, url) {
	console.log("ngrok err", err);
	console.log("ngrok url", url);
});
```

getting

```
ngrok err [Error: {"error_code":103,"status_code":502,"msg":"failed to start tunnel","details":{"err":"Custom subdomains are only available for paid plans. Signup at https://ngrok.com/signup"}}]
ngrok url undefined
```

**Comment by BenjaminConant** [comment]
@henninghorn thanks for the tip!

**Comment by danieldafoe** [comment]
Just so others viewing this are aware, the best workaround (for now) is indeed to change your entry for ngrok in your package.json to ```"ngrok": "~0.1.8"``` and then do an ```npm install``` in your project main directory again.

**Comment by bubenshchykov** [comment]
thanks @danieldafoe 
0.1.99 is also recommended on readme

status update on the issue itself:
- week ago ngrok owner promised to prepare bins with a fix for the root cause of this bug
- ngrok owner also notified about plans to drop support for ngrok 1 (corresponds to ~0.1.x on npm) in the end of a spring

as soon as we receive a new ngrok bins, this bug will fixed and covered by tests. thanks for patience!

**Comment by bubenshchykov** [comment]
guys, pls try 2.1.1 - issue should be fixed.
and covered by tests https://travis-ci.org/bubenshchykov/ngrok/jobs/115454650#L224-L314

**Comment by moeinrahimi** [comment]
I have this issue on 3.2.5

{
  error_code: 103,
  status_code: 502,
  msg: 'failed to start tunnel',
  details: { err: 'session closed' }
}

**Comment by swarooppuranik** [comment]
I am getting the same error. I am using python for ngrok. please advise

**Comment by bubenshchykov** [comment]
@swarooppuranik  How do you use this node.js module with python?

**Comment by swarooppuranik** [comment]
May be this is wrong thread. I am using pyngrok (python with ngrok). I am trying to establish connection with reserved tcp address and getting this error.

**Comment by bubenshchykov** [comment]
np, please contact binary owner at ngrok.com (contact@ngrok.com)
