### ISSUE TITLE
Help with grunt

### ISSUE THREAD

**Issue by elchiconube** [bubenshchykov/ngrok#40]
Hi! I want to integrate this on grunt but i don't know how. ¿Anyone can help me or give me some url with documentation? Thanks

**Comment by bubenshchykov** [comment]
Hi, sorry for a late reply!
Are you looking for something like that? https://www.npmjs.com/package/grunt-ngrok :)

**Comment by elchiconube** [comment]
Yai! Thanks but this project it's working with a Ngrok V1 and it's not working :(

**Comment by bubenshchykov** [comment]
I never tried grunt-ngrok, shared it just as a reference for you on how to integrate ngrok into grunt..
And yes the options are a bit different in ngrok 2 and they are described in readme https://github.com/bubenshchykov/ngrok/blob/master/README.md#options ;)

**Comment by bubenshchykov** [comment]
Closing the issue as it's nothing to do with the module. I hope you managed to make grunt integration working, should not be different from any other use cases!
