### ISSUE TITLE
Ngrok thinks I'm using custom sub domains?

### ISSUE THREAD

**Issue by jamen** [bubenshchykov/ngrok#42]
```
[Error: {"error_code":103,"status_code":502,"msg":"failed to start tunnel","details":{"err":"Custom subdomains are only available for paid plans. Upgrade at https://dashboard.ngrok.com/billing/plan"}}]
```

When using `ngrok.connect` with the correct token, I recieve this error.  I'm not setting `subdomain` in the options either.

**Comment by jamen** [comment]
Whoops, duplicate issue.

**Comment by jesperbruunhansen** [comment]
@jamen - I have the exact same problem, where did you find the solution/duplicate question?

**Comment by bubenshchykov** [comment]
try now, should be fixed :)
