### ISSUE TITLE
Error while lunching

### ISSUE THREAD

**Issue by esteban-uo** [bubenshchykov/ngrok#43]
Just today I started getting this error, Is this an expected one?

"there was an error while lunching ngrok: Error: panic: runtime error: invalid memory address or nil pointer dereference

github.com/inconshreveable/olive/recover.go:40
runtime/asm_amd64.s:403
reflect/value.go:419
reflect/value.go:296
github.com/codegangsta/inject/inject.go:102
<autogenerated>:30
<autogenerated>:132
github.com/inconshreveable/olive/recover.go:29
runtime/asm_amd64.s:401
runtime/panic.go:387
github.com/inconshreveable/olive/error.go:37 .

...... "

thanks!

**Comment by bubenshchykov** [comment]
@inconshreveable the first time it gives go errors :)

**Comment by bubenshchykov** [comment]
@esteban-uo is it a permanent error you still have?

**Comment by esteban-uo** [comment]
hi @bubenshchykov, not really, but it happens randomly and not too often

**Comment by bubenshchykov** [comment]
ok let's keep it here for some time - in case @inconshreveable notices it and pushes some go fix :)

**Comment by bubenshchykov** [comment]
ideally this ticked should be submitted to ngrok original github, but the problem is that ngrok 2.0 has not been open sourced yet. https://github.com/inconshreveable/ngrok#ngrok-20 

i still suggest you submit a ticket there, as it fails inside the go code.. i'll keep it open here to for a month too.

sorry for that!

**Comment by inconshreveable** [comment]
Yep, this is a known bug in ngrok, and shouldn't be open here.

**Comment by rapito** [comment]
@esteban-uo did you ever got around this issue, I get it every time now

**Comment by bubenshchykov** [comment]
@rapito @esteban-uo if the issue is still there, feel free to open an issue with platform details here - it should bring more attention :)
