### ISSUE TITLE
ngrok.disconnect not closing http tunnel (only https)

### ISSUE THREAD

**Issue by nojiek** [bubenshchykov/ngrok#54]
When two tunnels are opened simultaneously (`bind_tls: both` (this is default)), ngrok fails to close both tunnels when using the disconnect command.

Steps to Reproduce:

```js
ngrok.connect(bind_tls: 'both', port: currentPort), function((err, url) {
     console.log("Error Message: " + err);
     console.log('Ngrok URL: ' + url);
     console.log('Port: ' + currentPort);
}
```
Results in:
Error Message: null
Ngrok URL: https://030927d2.ngrok.io
Port: 3599

**This opens TWO tunnels: one at http and one at https**

```js
//Kills the ngrok tunnel
ngrok.disconnect(killUrl, function () {
    console.log('URL: ' + killUrl + ' has been killed.');
});
```
Results: 
URL: https://030927d2.ngrok.io has been killed.
{ [Error: socket hang up] code: 'ECONNRESET' }
![screen shot 2016-05-18 at 5 46 10 pm](https://cloud.githubusercontent.com/assets/1901154/15377326/88822ece-1d20-11e6-813b-b8f986b971f4.png)

**Note that the http tunnel remains open.**

**Comment by bubenshchykov** [comment]
hey @nojiek, great catch! :)

**Comment by vinceis1337** [comment]
Hello @bubenshchykov - I work with @nojiek and we have a workaround. We just wanted to let you know about the problem. Thanks!

**Comment by nojiek** [comment]
@bubenshchykov Thanks! Our work around is to just to not use "both" for now.

**Comment by bubenshchykov** [comment]
fixed, see test inside commit ;)

if you create default bind_tls=true tunnel and get let's say https://123.ngrok.io - then you can 
- either close both tunnels in two calls: ngrok.disconnect('https://123.ngrok.io'); ngrok.disconnect('http://123.ngrok.io')
- or close all tunells ngrok.disconnect() - but now it tracks and closes http tunnel too
- or kill entire process by ngrok.kill()
