### ISSUE TITLE
Missing ngrok binary doesn't clearly fail

### ISSUE THREAD

**Issue by gaieges** [bubenshchykov/ngrok#56]
Trying to set the authtoken without working ngrok binary results in a message of:

```
Error: cant set authtoken
```

Would be helpful to have a more clear message saying the binary doesnt exist.  Not sure if this happens elsewhere, but if it does, the message would be helpful there too.

**Comment by bubenshchykov** [comment]
Hi, makes sense! You are welcome to PR better error handling ;)
I'm personally more interested in "missing ngrok" problem. If ngrok binary can't be downloaded or unpacked - npm install should fail with an error message about it. How did you get module installed but binary missing?

**Comment by gaieges** [comment]
Consider the case where you package up an app for a different architecture than the one you’re currently running on: Your node_modules directory consists of the bin for the current architecture, but the destination system doesn't have a local binary that works with it’s architecture, or needs to nave the ```npm install -g``` on it.

Another way to solve this would be allow selections of what types of architectures you want installed, in the post install script.  Or perhaps enforce the ngrok binary install / exists on run time.

Open to other options, figured a quick log message would be easiest but I get where you’re coming from.

**Comment by bubenshchykov** [comment]
@gaieges i think the normal practice is to build (package) your app on machine which is 1:1 (platform and arch) with your prod machine, that applies to other npm modules too - and then distribute this build to your prod instances. that what heroku and other node clouds do. 

i'm really interested what your build process is?

**Comment by gaieges** [comment]
At the moment it's a jenkins job in AWS packaging the tool up into a deb using grunt. 

Agree with the general approach, but the intent is to put it on a armv7l box, which is where my problem comes in.  AFAIK, that's not something that AWS provides.  I could always get a Scaleway account but don't want to go through the hassle.

It'd be easiest to just include the binaries in the package (and tag it that way), but at the moment, instead I'm just provisioning the armv7l box with ngrok.  Not the prettiest but it works.

**Comment by bubenshchykov** [comment]
Got it :) At the beginning, I had all ngrok bins stored in a repo. But it made npm install taking too long, and then bins are always changing - so people asked for downloading only 1 bin during install. Like eg phantomjs or webdriver do. 

Your solution works, it might be also nice if we support NGROK_BIN_PROVISIONED=true env var, so npm install does not download anything, and instead checks if bin already exists :) I'll keep this issue open for some time to see if people are really annoyed by existing error handling (yes it's too simple now) - and thx for a nice talk!

**Comment by gaieges** [comment]
Would be cool to see something like NODE_NGROK_INSTALL_ARCH=x86_64,armv7l or something.  But not too big of a concern.  What do you think?

For sure!  Appreciated chatting with you as well.  If the current deploy process annoys me enough I'll spend some time on what we discussed.

**Comment by bubenshchykov** [comment]
will smth like that help? :)
https://github.com/bubenshchykov/ngrok/pull/57/files

**Comment by gaieges** [comment]
Sure will! That's great, thanks @bubenshchykov !

**Comment by bubenshchykov** [comment]
on npm, v2.2.2 ;)
