### ISSUE TITLE
global postinstall script fail on Windows 10 Bash

### ISSUE THREAD

**Issue by jdalton** [bubenshchykov/ngrok#58]
I'm hitting this issue on Windows 10 Bash.

``` bash
 projects npm i -g ngrok
/root/.nvm/versions/node/v4.4.7/bin/ngrok -> /root/.nvm/versions/node/v4.4.7/lib/node_modules/ngrok/bin/ngrok

> ngrok@2.2.2 postinstall /root/.nvm/versions/node/v4.4.7/lib/node_modules/ngrok
> node ./postinstall.js

module.js:442
    throw err;
    ^

Error: Cannot find module '/root/.nvm/versions/node/v4.4.7/lib/node_modules/ngrok/postinstall.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3 projects npm i -g ngrok
/root/.nvm/versions/node/v4.4.7/bin/ngrok -> /root/.nvm/versions/node/v4.4.7/lib/node_modules/ngrok/bin/ngrok

> ngrok@2.2.2 postinstall /root/.nvm/versions/node/v4.4.7/lib/node_modules/ngrok
> node ./postinstall.js

module.js:442
    throw err;
    ^

Error: Cannot find module '/root/.nvm/versions/node/v4.4.7/lib/node_modules/ngrok/postinstall.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
```

[npm-debug.log.txt](https://github.com/bubenshchykov/ngrok/files/405559/npm-debug.log.txt)

**Comment by bubenshchykov** [comment]
hi man! as a quick test, can you try  it with latest npm (3.10.5) ```npm i -g npm```
i see that your environment is a bit out of date :)
```
info using npm@2.15.8
3 info using node@v4.4.7
```

**Comment by jdalton** [comment]
Cool! I'm using the current lts release of node with an npm from this June. Its v2 but not out of date. The ngrok install works fine globally on Windows 10. Bash on Win10 is Ubuntu.

**Comment by jdalton** [comment]
Ok so I thought I saw it complete once. Here's the complete install:
```bash
 ~ npm i -g ngrok
/home/jdalton/.nvm/versions/node/v4.4.7/bin/ngrok -> /home/jdalton/.nvm/versions/node/v4.4.7/lib/node_modules/ngrok/bin/ngrok

> ngrok@2.2.2 postinstall /home/jdalton/.nvm/versions/node/v4.4.7/lib/node_modules/ngrok
> node ./postinstall.js

ngrok - downloading binary https://bin.equinox.io/a/b87faFPKrii/ngrok-2.1.1-linux-amd64.tar.gz ...
ngrok - binary downloaded...
ngrok - binary unpacked.
ngrok@2.2.2 /home/jdalton/.nvm/versions/node/v4.4.7/lib/node_modules/ngrok
├── lock@0.1.2
├── xtend@4.0.1
├── async@0.9.2
├── node-uuid@1.4.7
├── decompress-zip@0.3.0 (graceful-fs@4.1.5, q@1.4.1, mkpath@0.1.0, nopt@3.0.6, readable-stream@1.1.14, touch@0.0.3, binary@0.3.0)
├── request@2.74.0 (tunnel-agent@0.4.3, forever-agent@0.6.1, oauth-sign@0.8.2, caseless@0.11.0, is-typedarray@1.0.0, aws-sign2@0.6.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, aws4@1.4.1, extend@3.0.0, tough-cookie@2.3.1, qs@6.2.1, combined-stream@1.0.5, mime-types@2.1.11, form-data@1.0.0-rc4, bl@1.1.2, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6)
└── tar.gz@1.0.5 (commander@2.9.0, tar@2.2.1, bluebird@2.10.2, fstream@1.0.10, mout@0.11.1)
```
after than though `which ngrok` will report `/home/jdalton/.nvm/versions/node/v4.4.7/bin/ngrok`
but executing it is a noop it just goes back to bash.

**Comment by jdalton** [comment]
Is there some prerequisites that could be missing?

**Comment by jdalton** [comment]
It noops on npm v3 too.

**Comment by bubenshchykov** [comment]
No prerequisites.. 
For global install the flow is simple
- postinstall downloads proper ngrok bin and puts it to bin folder (./ngrok/bin executable)
- then package.json has this default ```"bin": {"ngrok": "./bin/ngrok"}``` which does this npm linking magic

Nothing really more..

There might be something wrong with timing of things: bin/ngrok is available only after postinstall, but npm symlinking seems to do smth even before.. That's why global install was failing before I put dummy ./bin/ngrok  https://github.com/bubenshchykov/ngrok/blob/master/bin/ngrok - I had to add this craziness after recent npm releases )

Few random ideas to try
- ```npm i github:bubenshchykov/ngrok#402db7f -g``` - including the whole "bin" folder into npm "files", don't believe in it)
- instead of text stub https://github.com/bubenshchykov/ngrok/blob/master/bin/ngrok, maybe chmod-ed executable with some dummy echo will work better

The way npm symlinking works has been changed over the last year I think, I might be missing some small detail - but honestly I'm out of good clues for now. Any ideas are welcome :)

**Comment by bubenshchykov** [comment]
@inconshreveable Alan people say ngrok is not working on Windows 10 bash, even if downloaded directly ngrok.com (#60)

**Comment by inconshreveable** [comment]
Thanks @bubenshchykov! I've had a few reports of this as well, it's a known issue. Win10 bash is still in beta and ngrok doesn't officially support it yet. I'll try to get an environment up asap and figure out what's going on.

**Comment by AlexHankins** [comment]
Workaround is to run `winpty ngrok` instead of just `ngrok`.  It looks like the problem is how Windows ngrok doesn't really know how to use the Windows console.

ngrok is certainly not alone in needing this treatment.
