### ISSUE TITLE
ngrok fails to start in Windows 10 Bash

### ISSUE THREAD

**Issue by Carpetfizz** [bubenshchykov/ngrok#60]
Hi,

I'm trying to use ngrok in Windows 10 Bash and I'm running into an issue. Nothing happens when I type in ngrok. Same thing occurs when I use the ngrok build from the official website.

Thanks for any information.

**Comment by bubenshchykov** [comment]
Hi, thanks for reporting! I think it's a duplicate of https://github.com/bubenshchykov/ngrok/issues/58 - could you please share few details there

**Comment by AlexHankins** [comment]
Use `winpty ngrok` instead of just `ngrok`.  Works for me.
