### ISSUE TITLE
Randomly ngrok stops working for me.

### ISSUE THREAD

**Issue by madhavc** [bubenshchykov/ngrok#61]
I am noticing that sometimes ngrok stops working for me. Any help? Here are the logs I have obtained

```
{"error_code":103,"status_code":502,"msg":"failed to start tunnel","details":{"err":"session closed"}}
```

```
{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":4040}
```

**Comment by bubenshchykov** [comment]
thx, are you creating multiple tunnels? share few more details, please
also os, node and npm version

**Comment by bubenshchykov** [comment]
there is a bunch of specs testing various ngrok tunenls, they are stable and green 
https://travis-ci.org/bubenshchykov/ngrok/jobs/150537893

so I'm wondering if it's some specific order of tunnel actions or maybe platform-related bug

**Comment by bubenshchykov** [comment]
might be fixed already, try latest
closing this one due to lack of details, feel free to open new one in case of problems!
