### ISSUE TITLE
ngrok 2.1.1 and sierra

### ISSUE THREAD

**Issue by alexbuijs** [bubenshchykov/ngrok#62]
I get some go-martini errors with ngrok 2.1.1 and OS X Sierra. Version 2.1.14 seems to do better. Please update to new ngrok version in postinstall hook.

**Comment by inconshreveable** [comment]
all fixes are mainstreamed and the latest version works on sierra. apologies on the lack of notification!

**Comment by bubenshchykov** [comment]
cool I'm switching to bins from ngrok site then if all tests are passing, better later than never :)

**Comment by bubenshchykov** [comment]
@alexbuijs thx, issue fixed - try latest!

**Comment by alexbuijs** [comment]
Thanks, great work!
