### ISSUE TITLE
Error when "sniffing" an iphone or ipad.

### ISSUE THREAD

**Issue by Kurara** [bubenshchykov/ngrok#66]
I have a problem that I'm trying to resolve (but I still don't know how you compile your code) in order to understand why my program is failing. When ngrok try to show me the error it fails, because MessageParts length is 0 and there is not a verificatin of this:

TypeError: undefined is not an object (evaluating 'messageParts[0].toString') 

Line: 

Console.prototype._generic = function(level, messageParts) {
    var message, messagePart, parameters, payload, _i, _len;
    message = messageParts[0].toString(); <-- length 0 I don't know why but in my case is 0.
    parameters = [];

To help you, I think the problem of the iphone, ipad with my code is in the css as I'm using css3 and maybe I'm forgetting something for apple. Or maybe is the ngmodel of angular2 that it's not well interpreted by iOS.

**Comment by Kurara** [comment]
Ok, my problem was dataPipe of angular. I don't know if that helps to understand why messageParts was null or size 0. I finally got to change the js code and write "no message" if messagePart[0] was null and I could see the details of the error.

Difference of error: [http://pasteboard.co/1QiBx9nyb.jpg](url)

**Comment by bubenshchykov** [comment]
hey, you sure you submit an issue to the right repo? :)
ngrok is not supposed to work in browser, neither I recognize posted pieces of code )

**Comment by Kurara** [comment]
I'm using ngrok to help debugging a web application in ipad as chrome developer tools are not able in tablet. I was looking for a solution to debug it and I found this plugin in internet. I'm using also weinre but weinre doesn't work with https so I add your ngrok. Maybe you are correct and it's a weinre problem. Sorry U-_- You can even delete the issue, it's for weinre. I'll post it on weinre. Thanks! My mistake >.<

**Comment by bubenshchykov** [comment]
Thanks a lot for submitting an issue, glad we figured it out!
