### ISSUE TITLE
Cant found tunnel created by node package . 

### ISSUE THREAD

**Issue by pociej** [bubenshchykov/ngrok#70]
Everytime im creating tunnel using node package 
i get the proper url no error. But when im trying to call this tunnel 
i see Tunnel {id}.ngrok.io not found .

**Comment by bubenshchykov** [comment]
Tunnel gets closed when you close your node process. Is it your case?

**Comment by pociej** [comment]
Im closing node process but before that im spawning new process and in this child process 
im creating ngrok tunnel .

**Comment by bubenshchykov** [comment]
do you use {detached: true} in this child process? otherwise if will be closed (and thus ngok tunnel) when parent process exits 
https://nodejs.org/api/child_process.html#child_process_options_detached

**Comment by bubenshchykov** [comment]
Closing issue for now. Feel free to re-open if {detached: true} doesn't help ;)
