### ISSUE TITLE
ngrok web UI url

### ISSUE THREAD

**Issue by keithws** [bubenshchykov/ngrok#72]
I know the web UI for ngrok is _usually_ http://127.0.0.1:4040, but that can be changed with the `web_addr` configuration option. Is there a way to get that value via this node wrapper?

**Comment by bubenshchykov** [comment]
at the moment, the only way to get or set web_addr is to use ngrok configuration file.
any configuration stored in ngrok.yml should be picked up and respected by this node wrapper

**Comment by faizaanceg** [comment]
[This line](https://github.com/bubenshchykov/ngrok/blob/master/index.js#L94) does exactly that. There is no way to extract it though.

**Comment by bubenshchykov** [comment]
merged, thx guys!
