### ISSUE TITLE
Error 'failed to deserialize request parameter'

### ISSUE THREAD

**Issue by scinos** [bubenshchykov/ngrok#75]
When running ngrok with

```
ngrok.connect({
    proto: 'http',
    addr: 3000,
    region: 'au'
}, function (err, url) {
    if (err) throw new Error(err);
});
```
The callback contains the error 'Error: failed to deserialise request parameter'. Debugging it seems to come from a 400 response when making a POST request to /api/tunnels.

The equivalent CLI command (`ngrok http --region au 3000`), it works as expected.

**Comment by bubenshchykov** [comment]
thanks, that's something new. works fine on mac os, but fails on linux
@inconshreveable could it be something changed in ngrok internal api (eg request parsing) recently?

**Comment by scinos** [comment]
For me it fails in osx too.
It was something that broke today, it was working fine ~7h hours ago.

**Comment by bubenshchykov** [comment]
ahh true! i'm checking module dependencies updates, but it can also be a ngrok bin autoupdate (@inconshreveable might help)

**Comment by inconshreveable** [comment]
@bubenshchykov this changed: https://ngrok.com/docs#compat-2.2 but i didn't expect it to break anything since it never actually worked in the first place

**Comment by bubenshchykov** [comment]
hmm I should be using application/json only, will check that

**Comment by inconshreveable** [comment]
@bubenshchykov looks like something wrong in the latest ngrok release with the client API, i'm rolling back, sorry about this.

**Comment by bubenshchykov** [comment]
works again, thanks all! :)

**Comment by inconshreveable** [comment]
Release 2.2.2 is out with a bugfix for this. ping me here if there's any trouble with that version

**Comment by bubenshchykov** [comment]
I set up a daily test run with 38 specs testing different ngrok options and tunnels, all green :)
https://travis-ci.org/bubenshchykov/ngrok

**Comment by scinos** [comment]
Works great now.
Than you both for fixing this so soon, and for this amazing software 🥇
