### ISSUE TITLE
Hangs when trying to use config "web_addr: false"

### ISSUE THREAD

**Issue by edwmurph** [bubenshchykov/ngrok#76]
I put the config file in the default location (~/.ngrok2/ngrok.yml) and verified that I can change the network address (ex. "web_addr: localhost:5050" works as expected). However when I try to disable the web UI ("web_addr: false"), ngrok just hangs until it eventually closes probably due to some timeout somewhere.

**Comment by bubenshchykov** [comment]
Hi, nice catch! web_addrs:false is not supported at the moment. The module needs this ngrok internal api (runs on same port as ngrok ui) to create and manage each new tunnel, and ngrok process is spawned only once to start the ngrok api.

There is an option to spawn ngrok each time tunnel is created, so we can stop relying on ngrok api. But I have tried that already and it was slow and buggy. I prefer to add a note about web_addrs:false in readme and leave it as it is. What do you think?

**Comment by edwmurph** [comment]
It'd be nice if it just closed when given "web_addr: false" instead of hanging but yes I think people would at least appreciate a note in the readme.

**Comment by bubenshchykov** [comment]
@edwmurph makes sense, will add it today
