### ISSUE TITLE
Why we need download ngrok binary file every time after install npm package?

### ISSUE THREAD

**Issue by gaoqiankun** [bubenshchykov/ngrok#83]
Hi, I found that ngrok binary file will be downloaded every time I install package use yarn。
How about save `ngrok.zip` file to `home` directory, and reuse it?

**Comment by bubenshchykov** [comment]
That would be a nice improvement! You'r welcome to submit a PR, I'm happy to review and accept it fast :)

**Comment by bubenshchykov** [comment]
fixed by amazing #85
