### ISSUE TITLE
Exit ngrok when there's nothing to sync

### ISSUE THREAD

**Issue by passboltUser** [bubenshchykov/ngrok#92]
Hello,
ngrok is used in `https://github.com/xybu/onedrived-dev`. What would be nice is if ngrok would exit if there's nothing to sync / if everything is synched. My Microsoft accounts get suspended and I think that's because too many requests are done to the Microsoft account. I'm not sure if ngrok can see when everything is synched completely or if it just provides a tunnel.

**Comment by bubenshchykov** [comment]
Hi, the responsibility of ngrok module is to create and stop tunnels, nothing else. Onedrived-dev can use ngrok api and close tunnels (or exit ngrok) any time it wants :) Please, create this issue there

**Comment by passboltUser** [comment]
Ok, thanks. Did that: https://github.com/xybu/onedrived-dev/issues/69
