### ISSUE TITLE
Ngrok always reconnecting

### ISSUE THREAD

**Issue by ashokkumar24** [bubenshchykov/ngrok#94]
I have installed `npm install ngrok` with version 2.2.8. Then I ran `ngrok http 8080`, I am getting the following error.
<img width="630" alt="screen shot 2017-10-18 at 6 32 20 pm" src="https://user-images.githubusercontent.com/19908047/31720039-0959a0fe-b433-11e7-88b8-8620cf7c4adc.png">

**Comment by bubenshchykov** [comment]
@inconshreveable hi Alan, is it a known issue?

**Comment by inconshreveable** [comment]
almost guaranteed to be a network/middlebox blocking ngrok

**Comment by bubenshchykov** [comment]
@ashokkumar24 can you confirm?
