### ISSUE TITLE
bin.equinox.io is down

### ISSUE THREAD

**Issue by milankragujevic** [bubenshchykov/ngrok#95]
Show Heroku error, is preventing me from download ngrok for Linux 64bit.

![2017-11-17_045043](https://user-images.githubusercontent.com/7611163/32928647-3fe238a2-cb53-11e7-85c8-256dc06c707c.jpg)

**Comment by bubenshchykov** [comment]
Hi, equinox guys have just confirmed that asset downloading issue is fixed. Please try again
Also, you can host ngrok
binary yourself and set NGROK_CDN_URL env var before npm install

**Comment by bubenshchykov** [comment]
feel free to reopen if the issue comes back, we might discuss a possibility to roll out alternative hosting

**Comment by alonroth** [comment]
@bubenshchykov equinox.io is down again
