### ISSUE TITLE
Stop using ~/.ngrok as a reliable location

### ISSUE THREAD

**Issue by damnhipster** [bubenshchykov/ngrok#96]
The `postinstall` script tries to download the relevant binary to the `~/.ngrok` location. Instead, I feel this should use the local `./node_modules` directory in which the npm module gets installed to.

That way, the module does not need to access the users home directory and make any modifications. There's less of an impact for damage to be done, and means that the installation process is less reliant on external directories to exist. 

At the moment, I already use the `~/.ngrok` location to store credentials, and this means the `postinstall` step fails, as a file already exists rather than some kind of directory. This kind of problem can be avoided entirely.

**Comment by bubenshchykov** [comment]
Hi, the process is next: we download binary, and then extract it. Extracted binary is always saved to ```./node_modules/ngrok/bin``` folder

As for download, previously we were using ```./node_modules/ngrok/bin``` for binary download too.
Recently we switched download to ```~/.ngrok```, so it can be used as a cache for multiple installs, to avoid downloading binary each time.
If there are problems accessing ```~/.ngrok```, then we fallback to ```./node_modules/ngrok/bin```, donwload binary and extract it in the same folder.
https://github.com/bubenshchykov/ngrok/blob/master/postinstall.js#L32

So it should work for you too. We can adjust this little safety guard to ensure that ```~./ngrok``` is a folder (not a file), and fallback to ```./node_modules/ngrok/bin``` if so. Will it work for you?

**Comment by damnhipster** [comment]
You should be able to make use of the npm cache for things like this.

Here's a [suggestion](https://github.com/npm/npm/issues/7029#issuecomment-68354982) of how to go about doing it. It does mean that you have to turn the binaries into a package.

**Comment by bubenshchykov** [comment]
That's an awesome suggestion!

I'm not sure if npm tries to fetch package content even if its package.json has OS/Arch restrictions. If it does, fetching all 10 bins during npm install won't be fun :) If npm is smart and checks dependency's package.json before downloading its content, then we can do it:

Pros
- npm install won't be dependent on external binary hosting at all. Yaaai!!!

Cons
- it has nothing to do with "binary caching" feature, it will be gone
- I should create, properly setup and maintain updates in 10 ngrok bin packages :)

**Comment by damnhipster** [comment]
You can use the **[os](https://docs.npmjs.com/files/package.json#os)** property to manage the OS restriction.

In terms of managing multiple binary packages, you could use [lerna](https://github.com/lerna/lerna) to manage it.

**Comment by bubenshchykov** [comment]
awesome, I like it! thx for the hints - I moved it to separate issue https://github.com/bubenshchykov/ngrok/issues/98
