### ISSUE TITLE
Ngrok is really slow

### ISSUE THREAD

**Issue by 87pancakes** [bubenshchykov/ngrok#99]
I have ngrok installed spare Mac that has a MAMP installation but the sites are really slow to load; some resources don't even load at all or partially.

Is this a limitation of the free plan?
Is there something wrong with ngroks sever or is it a local issue?

**Comment by bubenshchykov** [comment]
cc @inconshreveable

**Comment by bubenshchykov** [comment]
@87pancakes I run a static website with node.js with a free ngrok tunnel - works fast with all the assets!

Did you try to specify ngrok region closest to you?

**Comment by bubenshchykov** [comment]
@87pancakes if you experience the slowness, write contact@ngrok.com, they might help
closing this issue for now, as there is nothing else I can help with :)
feel free to re-open if needed!

**Comment by toverux** [comment]
This issue is not in the good repo anyway, I'm sure that @87pancakes doesn't even uses the npm module.

@bubenshchykov Why not renaming the repo to "node-ngrok" as per the conventions? With the repo name and the image at the top of the readme, it really looks like the official ngrok repo at a first glance.

**Comment by bubenshchykov** [comment]
@toverux great suggestion! I'll think about the options

**Comment by McOmolloDotJava** [comment]
Hv been using ngrok too ,,, its working well. Bt its important to note that its not for production environment

**Comment by webhacking** [comment]
I have the same problem. Did you find a solution?
I'm paid a plan;;;;; sibar

**Comment by vamsikrishnachevikala-web** [comment]
I am using the ngrok in ubuntu 18.04 for live streaming. speed of the my live streaming is extremely slow. Can any one tell me the reason for that and also provide me the solution to solve the issue. 
Thanks in advance.
